SELECT
    T1.ORDER_M_ID        AS ORDER_M_ID,
    T1.SOURCE_SYS_ID     AS SOURCE_SYS_ID,
    T1.CUST_ID           AS CUST_ID,
    T1.SOURCE_ORDER_ID   AS SOURCE_ORDER_ID,
    T1.IMG_ID_APID       AS IMG_ID_APID,
    T1.IMG_STORE_PATH    AS IMG_STORE_PATH,
    T2.LINK_TYPE         AS LINK_TYPE,
    T2.LINK              AS LINK,
    T2.PARAMETER         AS PARAMETER,
    T2.BROWSER           AS BROWSER,
    T2.ENCRYPTION_METHOD AS ENCRYPTION_METHOD,
    T2.ENCRYPTION_KEY    AS ENCRYPTION_KEY
FROM
    ORDER_MAIN_OSP T1
JOIN
    ORDER_IMAGE_SETTING T2
ON
    T1.SOURCE_SYS_ID = T2.SOURCE_SYS_ID
WHERE
    T1.ORDER_M_ID = :ORDER_M_ID