SELECT DISTINCT
    T1.ORDER_M_ID      AS ORDER_M_ID,
    T1.OSP_CREATE_TIME AS OSP_CREATE_TIME,
    T1.UPDATE_DATE     AS UPDATE_DATE,
    T1.MSISDN          AS MSISDN,
    T1.ORDER_STATUS    AS ORDER_STATUS,
    T2.STATUS_NAME     AS ORDER_STATUS_TEXT,
    T3.REASON_TEXT     AS PROCESS_REASON_TEXT,
    T1.COMMMENT        AS COMMMENT
FROM
    ORDER_MAIN_OSP T1
LEFT JOIN
    SYS_ORDER_STATUS_SETTING T2
ON
    T1.ORDER_STATUS=T2.STATUS_ID
LEFT JOIN
    SYS_REASON T3
ON
    T1.PROCESS_REASON = T3.REASON_ID
WHERE
    $P{CONDITION}
ORDER BY
    T1.OSP_CREATE_TIME