package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuzContent generated by hbm2java
 */
@Entity
@Table(name="BUZ_CONTENT")
public class BuzContent  implements java.io.Serializable {


     private String contentId;
     private String contentName;
     private String templateType;
     private String link;
     private String parameter;
     private String contentOpenType;
     private String openBrowser;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public BuzContent() {
    }

	
    public BuzContent(String contentId, String templateType, Date createDate, String createUser) {
        this.contentId = contentId;
        this.templateType = templateType;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public BuzContent(String contentId, String contentName, String templateType, String link, String parameter, String contentOpenType, String openBrowser, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.contentId = contentId;
       this.contentName = contentName;
       this.templateType = templateType;
       this.link = link;
       this.parameter = parameter;
       this.contentOpenType = contentOpenType;
       this.openBrowser = openBrowser;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id 

    
    @Column(name="CONTENT_ID", unique=true, nullable=false, length=40)
    public String getContentId() {
        return this.contentId;
    }
    
    public void setContentId(String contentId) {
        this.contentId = contentId;
    }

    
    @Column(name="CONTENT_NAME", length=200)
    public String getContentName() {
        return this.contentName;
    }
    
    public void setContentName(String contentName) {
        this.contentName = contentName;
    }

    
    @Column(name="TEMPLATE_TYPE", nullable=false, length=20)
    public String getTemplateType() {
        return this.templateType;
    }
    
    public void setTemplateType(String templateType) {
        this.templateType = templateType;
    }

    
    @Column(name="LINK", length=2000)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    
    @Column(name="PARAMETER", length=2000)
    public String getParameter() {
        return this.parameter;
    }
    
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    
    @Column(name="CONTENT_OPEN_TYPE", length=5)
    public String getContentOpenType() {
        return this.contentOpenType;
    }
    
    public void setContentOpenType(String contentOpenType) {
        this.contentOpenType = contentOpenType;
    }

    
    @Column(name="OPEN_BROWSER", length=20)
    public String getOpenBrowser() {
        return this.openBrowser;
    }
    
    public void setOpenBrowser(String openBrowser) {
        this.openBrowser = openBrowser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


