package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuzFlowStep generated by hbm2java
 */
@Entity
@Table(name="BUZ_FLOW_STEP")
public class BuzFlowStep  implements java.io.Serializable {


     private BuzFlowStepId id;
     private String stepName;
     private BigDecimal sortSequence;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public BuzFlowStep() {
    }

	
    public BuzFlowStep(BuzFlowStepId id, String stepName, BigDecimal sortSequence, Date createDate, String createUser) {
        this.id = id;
        this.stepName = stepName;
        this.sortSequence = sortSequence;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public BuzFlowStep(BuzFlowStepId id, String stepName, BigDecimal sortSequence, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.id = id;
       this.stepName = stepName;
       this.sortSequence = sortSequence;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="flowId", column=@Column(name="FLOW_ID", nullable=false, length=40) ), 
        @AttributeOverride(name="stepId", column=@Column(name="STEP_ID", nullable=false, length=40) ) } )
    public BuzFlowStepId getId() {
        return this.id;
    }
    
    public void setId(BuzFlowStepId id) {
        this.id = id;
    }

    
    @Column(name="STEP_NAME", nullable=false, length=50)
    public String getStepName() {
        return this.stepName;
    }
    
    public void setStepName(String stepName) {
        this.stepName = stepName;
    }

    
    @Column(name="SORT_SEQUENCE", nullable=false, precision=4, scale=1)
    public BigDecimal getSortSequence() {
        return this.sortSequence;
    }
    
    public void setSortSequence(BigDecimal sortSequence) {
        this.sortSequence = sortSequence;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


