package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuzFlow generated by hbm2java
 */
@Entity
@Table(name="BUZ_FLOW")
public class BuzFlow  implements java.io.Serializable {


     private String flowId;
     private String flowName;
     private String orderTypeId;
     private String orderTypeName;
     private String menuId;
     private String skillId;
     private String sourceSysId;
     private String active;
     private String btnTempSave;
     private String btnTempLeave;
     private String btnSuccess;
     private String btnFail;
     private String btnShowMessage;
     private String btnSysReply;
     private String btnShowSourceDoc;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private String btnChangeOrderType;

    public BuzFlow() {
    }

	
    public BuzFlow(String flowId, String flowName, String orderTypeId, String menuId, String skillId, String sourceSysId, String active, String btnTempSave, String btnTempLeave, String btnSuccess, String btnFail, String btnShowMessage, String btnSysReply, String btnShowSourceDoc, Date createDate, String createUser, String btnChangeOrderType) {
        this.flowId = flowId;
        this.flowName = flowName;
        this.orderTypeId = orderTypeId;
        this.menuId = menuId;
        this.skillId = skillId;
        this.sourceSysId = sourceSysId;
        this.active = active;
        this.btnTempSave = btnTempSave;
        this.btnTempLeave = btnTempLeave;
        this.btnSuccess = btnSuccess;
        this.btnFail = btnFail;
        this.btnShowMessage = btnShowMessage;
        this.btnSysReply = btnSysReply;
        this.btnShowSourceDoc = btnShowSourceDoc;
        this.createDate = createDate;
        this.createUser = createUser;
        this.btnChangeOrderType = btnChangeOrderType;
    }
    public BuzFlow(String flowId, String flowName, String orderTypeId, String orderTypeName, String menuId, String skillId, String sourceSysId, String active, String btnTempSave, String btnTempLeave, String btnSuccess, String btnFail, String btnShowMessage, String btnSysReply, String btnShowSourceDoc, Date createDate, String createUser, Date updateDate, String updateUser, String btnChangeOrderType) {
       this.flowId = flowId;
       this.flowName = flowName;
       this.orderTypeId = orderTypeId;
       this.orderTypeName = orderTypeName;
       this.menuId = menuId;
       this.skillId = skillId;
       this.sourceSysId = sourceSysId;
       this.active = active;
       this.btnTempSave = btnTempSave;
       this.btnTempLeave = btnTempLeave;
       this.btnSuccess = btnSuccess;
       this.btnFail = btnFail;
       this.btnShowMessage = btnShowMessage;
       this.btnSysReply = btnSysReply;
       this.btnShowSourceDoc = btnShowSourceDoc;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.btnChangeOrderType = btnChangeOrderType;
    }
   
     @Id 

    
    @Column(name="FLOW_ID", unique=true, nullable=false, length=40)
    public String getFlowId() {
        return this.flowId;
    }
    
    public void setFlowId(String flowId) {
        this.flowId = flowId;
    }

    
    @Column(name="FLOW_NAME", nullable=false, length=50)
    public String getFlowName() {
        return this.flowName;
    }
    
    public void setFlowName(String flowName) {
        this.flowName = flowName;
    }

    
    @Column(name="ORDER_TYPE_ID", nullable=false, length=40)
    public String getOrderTypeId() {
        return this.orderTypeId;
    }
    
    public void setOrderTypeId(String orderTypeId) {
        this.orderTypeId = orderTypeId;
    }

    
    @Column(name="ORDER_TYPE_NAME", length=100)
    public String getOrderTypeName() {
        return this.orderTypeName;
    }
    
    public void setOrderTypeName(String orderTypeName) {
        this.orderTypeName = orderTypeName;
    }

    
    @Column(name="MENU_ID", nullable=false, length=40)
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    
    @Column(name="SKILL_ID", nullable=false, length=40)
    public String getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(String skillId) {
        this.skillId = skillId;
    }

    
    @Column(name="SOURCE_SYS_ID", nullable=false, length=20)
    public String getSourceSysId() {
        return this.sourceSysId;
    }
    
    public void setSourceSysId(String sourceSysId) {
        this.sourceSysId = sourceSysId;
    }

    
    @Column(name="ACTIVE", nullable=false, length=5)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }

    
    @Column(name="BTN_TEMP_SAVE", nullable=false, length=5)
    public String getBtnTempSave() {
        return this.btnTempSave;
    }
    
    public void setBtnTempSave(String btnTempSave) {
        this.btnTempSave = btnTempSave;
    }

    
    @Column(name="BTN_TEMP_LEAVE", nullable=false, length=5)
    public String getBtnTempLeave() {
        return this.btnTempLeave;
    }
    
    public void setBtnTempLeave(String btnTempLeave) {
        this.btnTempLeave = btnTempLeave;
    }

    
    @Column(name="BTN_SUCCESS", nullable=false, length=5)
    public String getBtnSuccess() {
        return this.btnSuccess;
    }
    
    public void setBtnSuccess(String btnSuccess) {
        this.btnSuccess = btnSuccess;
    }

    
    @Column(name="BTN_FAIL", nullable=false, length=5)
    public String getBtnFail() {
        return this.btnFail;
    }
    
    public void setBtnFail(String btnFail) {
        this.btnFail = btnFail;
    }

    
    @Column(name="BTN_SHOW_MESSAGE", nullable=false, length=5)
    public String getBtnShowMessage() {
        return this.btnShowMessage;
    }
    
    public void setBtnShowMessage(String btnShowMessage) {
        this.btnShowMessage = btnShowMessage;
    }

    
    @Column(name="BTN_SYS_REPLY", nullable=false, length=5)
    public String getBtnSysReply() {
        return this.btnSysReply;
    }
    
    public void setBtnSysReply(String btnSysReply) {
        this.btnSysReply = btnSysReply;
    }

    
    @Column(name="BTN_SHOW_SOURCE_DOC", nullable=false, length=5)
    public String getBtnShowSourceDoc() {
        return this.btnShowSourceDoc;
    }
    
    public void setBtnShowSourceDoc(String btnShowSourceDoc) {
        this.btnShowSourceDoc = btnShowSourceDoc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    
    @Column(name="BTN_CHANGE_ORDER_TYPE", nullable=false, length=5)
    public String getBtnChangeOrderType() {
        return this.btnChangeOrderType;
    }
    
    public void setBtnChangeOrderType(String btnChangeOrderType) {
        this.btnChangeOrderType = btnChangeOrderType;
    }




}


