package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 ¤U¤È 01:10:48 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BuzItemId generated by hbm2java
 */
@Embeddable
public class BuzItemId  implements java.io.Serializable {


     private String itemType;
     private String itemId;

    public BuzItemId() {
    }

    public BuzItemId(String itemType, String itemId) {
       this.itemType = itemType;
       this.itemId = itemId;
    }
   


    @Column(name="ITEM_TYPE", nullable=false, length=20)
    public String getItemType() {
        return this.itemType;
    }
    
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }


    @Column(name="ITEM_ID", nullable=false, length=20)
    public String getItemId() {
        return this.itemId;
    }
    
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BuzItemId) ) return false;
		 BuzItemId castOther = ( BuzItemId ) other; 
         
		 return ( (this.getItemType()==castOther.getItemType()) || ( this.getItemType()!=null && castOther.getItemType()!=null && this.getItemType().equals(castOther.getItemType()) ) )
 && ( (this.getItemId()==castOther.getItemId()) || ( this.getItemId()!=null && castOther.getItemId()!=null && this.getItemId().equals(castOther.getItemId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getItemType() == null ? 0 : this.getItemType().hashCode() );
         result = 37 * result + ( getItemId() == null ? 0 : this.getItemId().hashCode() );
         return result;
   }   


}


