package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuzItem generated by hbm2java
 */
@Entity
@Table(name="BUZ_ITEM")
public class BuzItem  implements java.io.Serializable {


     private BuzItemId id;
     private String itemName;
     private BigDecimal reserv1;
     private String reserv2;
     private String reserv3;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public BuzItem() {
    }

	
    public BuzItem(BuzItemId id, String itemName, Date createDate, String createUser) {
        this.id = id;
        this.itemName = itemName;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public BuzItem(BuzItemId id, String itemName, BigDecimal reserv1, String reserv2, String reserv3, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.id = id;
       this.itemName = itemName;
       this.reserv1 = reserv1;
       this.reserv2 = reserv2;
       this.reserv3 = reserv3;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemType", column=@Column(name="ITEM_TYPE", nullable=false, length=20) ), 
        @AttributeOverride(name="itemId", column=@Column(name="ITEM_ID", nullable=false, length=20) ) } )
    public BuzItemId getId() {
        return this.id;
    }
    
    public void setId(BuzItemId id) {
        this.id = id;
    }

    
    @Column(name="ITEM_NAME", nullable=false, length=100)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    
    @Column(name="RESERV1", precision=4, scale=1)
    public BigDecimal getReserv1() {
        return this.reserv1;
    }
    
    public void setReserv1(BigDecimal reserv1) {
        this.reserv1 = reserv1;
    }

    
    @Column(name="RESERV2", length=100)
    public String getReserv2() {
        return this.reserv2;
    }
    
    public void setReserv2(String reserv2) {
        this.reserv2 = reserv2;
    }

    
    @Column(name="RESERV3", length=500)
    public String getReserv3() {
        return this.reserv3;
    }
    
    public void setReserv3(String reserv3) {
        this.reserv3 = reserv3;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


