package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuzRecordRoutine generated by hbm2java
 */
@Entity
@Table(name="BUZ_RECORD_ROUTINE")
public class BuzRecordRoutine  implements java.io.Serializable {


     private BuzRecordRoutineId id;
     private String itemName;
     private String itemValue;
     private BigDecimal sortSequence;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public BuzRecordRoutine() {
    }

	
    public BuzRecordRoutine(BuzRecordRoutineId id, String itemName, BigDecimal sortSequence, Date createDate, String createUser) {
        this.id = id;
        this.itemName = itemName;
        this.sortSequence = sortSequence;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public BuzRecordRoutine(BuzRecordRoutineId id, String itemName, String itemValue, BigDecimal sortSequence, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.id = id;
       this.itemName = itemName;
       this.itemValue = itemValue;
       this.sortSequence = sortSequence;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="processUserId", column=@Column(name="PROCESS_USER_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="processDate", column=@Column(name="PROCESS_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="contentId", column=@Column(name="CONTENT_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="itemId", column=@Column(name="ITEM_ID", nullable=false, length=20) ) } )
    public BuzRecordRoutineId getId() {
        return this.id;
    }
    
    public void setId(BuzRecordRoutineId id) {
        this.id = id;
    }

    
    @Column(name="ITEM_NAME", nullable=false, length=100)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    
    @Column(name="ITEM_VALUE", length=20)
    public String getItemValue() {
        return this.itemValue;
    }
    
    public void setItemValue(String itemValue) {
        this.itemValue = itemValue;
    }

    
    @Column(name="SORT_SEQUENCE", nullable=false, precision=4, scale=1)
    public BigDecimal getSortSequence() {
        return this.sortSequence;
    }
    
    public void setSortSequence(BigDecimal sortSequence) {
        this.sortSequence = sortSequence;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


