package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuzStepPage generated by hbm2java
 */
@Entity
@Table(name="BUZ_STEP_PAGE")
public class BuzStepPage  implements java.io.Serializable {


     private BuzStepPageId id;
     private String contentName;
     private BigDecimal sortSequence;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public BuzStepPage() {
    }

	
    public BuzStepPage(BuzStepPageId id, BigDecimal sortSequence, Date createDate, String createUser) {
        this.id = id;
        this.sortSequence = sortSequence;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public BuzStepPage(BuzStepPageId id, String contentName, BigDecimal sortSequence, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.id = id;
       this.contentName = contentName;
       this.sortSequence = sortSequence;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="flowId", column=@Column(name="FLOW_ID", nullable=false, length=40) ), 
        @AttributeOverride(name="stepId", column=@Column(name="STEP_ID", nullable=false, length=40) ), 
        @AttributeOverride(name="contentId", column=@Column(name="CONTENT_ID", nullable=false, length=40) ) } )
    public BuzStepPageId getId() {
        return this.id;
    }
    
    public void setId(BuzStepPageId id) {
        this.id = id;
    }

    
    @Column(name="CONTENT_NAME", length=2000)
    public String getContentName() {
        return this.contentName;
    }
    
    public void setContentName(String contentName) {
        this.contentName = contentName;
    }

    
    @Column(name="SORT_SEQUENCE", nullable=false, precision=4, scale=1)
    public BigDecimal getSortSequence() {
        return this.sortSequence;
    }
    
    public void setSortSequence(BigDecimal sortSequence) {
        this.sortSequence = sortSequence;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


