package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BuzVPosCompareResult generated by hbm2java
 */
@Entity
@Table(name="BUZ_V_POS_COMPARE_RESULT")
public class BuzVPosCompareResult  implements java.io.Serializable {


     private BuzVPosCompareResultId id;
     private BigDecimal VPosMoney;
     private BigDecimal VPosNumberPeriods;
     private String VPosRemark;
     private String aimsOrderId;
     private String aimsShippingId;
     private String aimsMsisdn;
     private BigDecimal aimsActualPayment;
     private String compareResult;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private String aimsAuthCode;

    public BuzVPosCompareResult() {
    }

	
    public BuzVPosCompareResult(BuzVPosCompareResultId id, Date createDate, String createUser) {
        this.id = id;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public BuzVPosCompareResult(BuzVPosCompareResultId id, BigDecimal VPosMoney, BigDecimal VPosNumberPeriods, String VPosRemark, String aimsOrderId, String aimsShippingId, String aimsMsisdn, BigDecimal aimsActualPayment, String compareResult, Date createDate, String createUser, Date updateDate, String updateUser, String aimsAuthCode) {
       this.id = id;
       this.VPosMoney = VPosMoney;
       this.VPosNumberPeriods = VPosNumberPeriods;
       this.VPosRemark = VPosRemark;
       this.aimsOrderId = aimsOrderId;
       this.aimsShippingId = aimsShippingId;
       this.aimsMsisdn = aimsMsisdn;
       this.aimsActualPayment = aimsActualPayment;
       this.compareResult = compareResult;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.aimsAuthCode = aimsAuthCode;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="compareId", column=@Column(name="COMPARE_ID", nullable=false, length=36) ), 
        @AttributeOverride(name="VPosAuthCode", column=@Column(name="V_POS_AUTH_CODE", nullable=false, length=20) ) } )
    public BuzVPosCompareResultId getId() {
        return this.id;
    }
    
    public void setId(BuzVPosCompareResultId id) {
        this.id = id;
    }

    
    @Column(name="V_POS_MONEY", precision=8, scale=4)
    public BigDecimal getVPosMoney() {
        return this.VPosMoney;
    }
    
    public void setVPosMoney(BigDecimal VPosMoney) {
        this.VPosMoney = VPosMoney;
    }

    
    @Column(name="V_POS_NUMBER_PERIODS", precision=4, scale=1)
    public BigDecimal getVPosNumberPeriods() {
        return this.VPosNumberPeriods;
    }
    
    public void setVPosNumberPeriods(BigDecimal VPosNumberPeriods) {
        this.VPosNumberPeriods = VPosNumberPeriods;
    }

    
    @Column(name="V_POS_REMARK", length=500)
    public String getVPosRemark() {
        return this.VPosRemark;
    }
    
    public void setVPosRemark(String VPosRemark) {
        this.VPosRemark = VPosRemark;
    }

    
    @Column(name="AIMS_ORDER_ID", length=50)
    public String getAimsOrderId() {
        return this.aimsOrderId;
    }
    
    public void setAimsOrderId(String aimsOrderId) {
        this.aimsOrderId = aimsOrderId;
    }

    
    @Column(name="AIMS_SHIPPING_ID", length=20)
    public String getAimsShippingId() {
        return this.aimsShippingId;
    }
    
    public void setAimsShippingId(String aimsShippingId) {
        this.aimsShippingId = aimsShippingId;
    }

    
    @Column(name="AIMS_MSISDN", length=50)
    public String getAimsMsisdn() {
        return this.aimsMsisdn;
    }
    
    public void setAimsMsisdn(String aimsMsisdn) {
        this.aimsMsisdn = aimsMsisdn;
    }

    
    @Column(name="AIMS_ACTUAL_PAYMENT", precision=8, scale=4)
    public BigDecimal getAimsActualPayment() {
        return this.aimsActualPayment;
    }
    
    public void setAimsActualPayment(BigDecimal aimsActualPayment) {
        this.aimsActualPayment = aimsActualPayment;
    }

    
    @Column(name="COMPARE_RESULT", length=50)
    public String getCompareResult() {
        return this.compareResult;
    }
    
    public void setCompareResult(String compareResult) {
        this.compareResult = compareResult;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    
    @Column(name="AIMS_AUTH_CODE", length=20)
    public String getAimsAuthCode() {
        return this.aimsAuthCode;
    }
    
    public void setAimsAuthCode(String aimsAuthCode) {
        this.aimsAuthCode = aimsAuthCode;
    }




}


