package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 ¤U¤È 01:10:48 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BuzVPosCompareResultId generated by hbm2java
 */
@Embeddable
public class BuzVPosCompareResultId  implements java.io.Serializable {


     private String compareId;
     private String VPosAuthCode;

    public BuzVPosCompareResultId() {
    }

    public BuzVPosCompareResultId(String compareId, String VPosAuthCode) {
       this.compareId = compareId;
       this.VPosAuthCode = VPosAuthCode;
    }
   


    @Column(name="COMPARE_ID", nullable=false, length=36)
    public String getCompareId() {
        return this.compareId;
    }
    
    public void setCompareId(String compareId) {
        this.compareId = compareId;
    }


    @Column(name="V_POS_AUTH_CODE", nullable=false, length=20)
    public String getVPosAuthCode() {
        return this.VPosAuthCode;
    }
    
    public void setVPosAuthCode(String VPosAuthCode) {
        this.VPosAuthCode = VPosAuthCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BuzVPosCompareResultId) ) return false;
		 BuzVPosCompareResultId castOther = ( BuzVPosCompareResultId ) other; 
         
		 return ( (this.getCompareId()==castOther.getCompareId()) || ( this.getCompareId()!=null && castOther.getCompareId()!=null && this.getCompareId().equals(castOther.getCompareId()) ) )
 && ( (this.getVPosAuthCode()==castOther.getVPosAuthCode()) || ( this.getVPosAuthCode()!=null && castOther.getVPosAuthCode()!=null && this.getVPosAuthCode().equals(castOther.getVPosAuthCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCompareId() == null ? 0 : this.getCompareId().hashCode() );
         result = 37 * result + ( getVPosAuthCode() == null ? 0 : this.getVPosAuthCode().hashCode() );
         return result;
   }   


}


