package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DispatchMemberConfig generated by hbm2java
 */
@Entity
@Table(name="DISPATCH_MEMBER_CONFIG")
public class DispatchMemberConfig  implements java.io.Serializable {


     private String dispMemberId;
     private String empno;
     private String empname;
     private Date pauseStartTime;
     private Date pauseEndTime;
     private String active;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public DispatchMemberConfig() {
    }

	
    public DispatchMemberConfig(String dispMemberId, String empno, Date pauseStartTime, String active, Date createDate, String createUser) {
        this.dispMemberId = dispMemberId;
        this.empno = empno;
        this.pauseStartTime = pauseStartTime;
        this.active = active;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public DispatchMemberConfig(String dispMemberId, String empno, String empname, Date pauseStartTime, Date pauseEndTime, String active, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.dispMemberId = dispMemberId;
       this.empno = empno;
       this.empname = empname;
       this.pauseStartTime = pauseStartTime;
       this.pauseEndTime = pauseEndTime;
       this.active = active;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id 

    
    @Column(name="DISP_MEMBER_ID", unique=true, nullable=false, length=36)
    public String getDispMemberId() {
        return this.dispMemberId;
    }
    
    public void setDispMemberId(String dispMemberId) {
        this.dispMemberId = dispMemberId;
    }

    
    @Column(name="EMPNO", nullable=false, length=20)
    public String getEmpno() {
        return this.empno;
    }
    
    public void setEmpno(String empno) {
        this.empno = empno;
    }

    
    @Column(name="EMPNAME", length=40)
    public String getEmpname() {
        return this.empname;
    }
    
    public void setEmpname(String empname) {
        this.empname = empname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PAUSE_START_TIME", nullable=false, length=7)
    public Date getPauseStartTime() {
        return this.pauseStartTime;
    }
    
    public void setPauseStartTime(Date pauseStartTime) {
        this.pauseStartTime = pauseStartTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PAUSE_END_TIME", length=7)
    public Date getPauseEndTime() {
        return this.pauseEndTime;
    }
    
    public void setPauseEndTime(Date pauseEndTime) {
        this.pauseEndTime = pauseEndTime;
    }

    
    @Column(name="ACTIVE", nullable=false, length=5)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


