package com.fet.crm.osp.platform.core.db.model;
// Generated May 10, 2017 12:40:59 AM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HrmMember generated by hbm2java
 */
@Entity
@Table(name="HRM_MEMBER")
public class HrmMember  implements java.io.Serializable {


     private HrmMemberId id;
     private String deptchiname;
     private String empname;
     private String engname;
     private String aliasname;
     private String email;
     private String costcenter;
     private String teamGroup;
     private Date createDate;
     private String createUser;

    public HrmMember() {
    }

	
    public HrmMember(HrmMemberId id, String deptchiname, String teamGroup, Date createDate, String createUser) {
        this.id = id;
        this.deptchiname = deptchiname;
        this.teamGroup = teamGroup;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public HrmMember(HrmMemberId id, String deptchiname, String empname, String engname, String aliasname, String email, String costcenter, String teamGroup, Date createDate, String createUser) {
       this.id = id;
       this.deptchiname = deptchiname;
       this.empname = empname;
       this.engname = engname;
       this.aliasname = aliasname;
       this.email = email;
       this.costcenter = costcenter;
       this.teamGroup = teamGroup;
       this.createDate = createDate;
       this.createUser = createUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="empno", column=@Column(name="EMPNO", nullable=false, length=10) ), 
        @AttributeOverride(name="deptcode", column=@Column(name="DEPTCODE", nullable=false, length=40) ) } )
    public HrmMemberId getId() {
        return this.id;
    }
    
    public void setId(HrmMemberId id) {
        this.id = id;
    }

    
    @Column(name="DEPTCHINAME", nullable=false, length=100)
    public String getDeptchiname() {
        return this.deptchiname;
    }
    
    public void setDeptchiname(String deptchiname) {
        this.deptchiname = deptchiname;
    }

    
    @Column(name="EMPNAME", length=30)
    public String getEmpname() {
        return this.empname;
    }
    
    public void setEmpname(String empname) {
        this.empname = empname;
    }

    
    @Column(name="ENGNAME", length=40)
    public String getEngname() {
        return this.engname;
    }
    
    public void setEngname(String engname) {
        this.engname = engname;
    }

    
    @Column(name="ALIASNAME", length=40)
    public String getAliasname() {
        return this.aliasname;
    }
    
    public void setAliasname(String aliasname) {
        this.aliasname = aliasname;
    }

    
    @Column(name="EMAIL", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="COSTCENTER", length=30)
    public String getCostcenter() {
        return this.costcenter;
    }
    
    public void setCostcenter(String costcenter) {
        this.costcenter = costcenter;
    }

    
    @Column(name="TEAM_GROUP", nullable=false, length=30)
    public String getTeamGroup() {
        return this.teamGroup;
    }
    
    public void setTeamGroup(String teamGroup) {
        this.teamGroup = teamGroup;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }




}


