package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/5/18 下午 05:26:30 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderDispatchNotify generated by hbm2java
 */
@Entity
@Table(name="ORDER_DISPATCH_NOTIFY")
public class OrderDispatchNotify  implements java.io.Serializable {


     private OrderDispatchNotifyId id;
     private String processUserId;
     private Date createDate;

    public OrderDispatchNotify() {
    }

    public OrderDispatchNotify(OrderDispatchNotifyId id, String processUserId, Date createDate) {
       this.id = id;
       this.processUserId = processUserId;
       this.createDate = createDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="batchNo", column=@Column(name="BATCH_NO", nullable=false, length=36) ), 
        @AttributeOverride(name="orderMId", column=@Column(name="ORDER_M_ID", nullable=false, length=36) ) } )
    public OrderDispatchNotifyId getId() {
        return this.id;
    }
    
    public void setId(OrderDispatchNotifyId id) {
        this.id = id;
    }

    
    @Column(name="PROCESS_USER_ID", nullable=false, length=20)
    public String getProcessUserId() {
        return this.processUserId;
    }
    
    public void setProcessUserId(String processUserId) {
        this.processUserId = processUserId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


