package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/6/8 下午 04:15:10 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderOperateRecords generated by hbm2java
 */
@Entity
@Table(name="ORDER_OPERATE_RECORDS")
public class OrderOperateRecords  implements java.io.Serializable {


     private String orderOpId;
     private String orderMId;
     private String msisdn;
     private String actionType;
     private Date executeTime;
     private String processResult;
     private String problemReason;
     private Date createDate;
     private String createUser;
     private String actionContent;

    public OrderOperateRecords() {
    }

	
    public OrderOperateRecords(String orderOpId, String orderMId, String actionType, Date executeTime, Date createDate, String createUser, String actionContent) {
        this.orderOpId = orderOpId;
        this.orderMId = orderMId;
        this.actionType = actionType;
        this.executeTime = executeTime;
        this.createDate = createDate;
        this.createUser = createUser;
        this.actionContent = actionContent;
    }
    public OrderOperateRecords(String orderOpId, String orderMId, String msisdn, String actionType, Date executeTime, String processResult, String problemReason, Date createDate, String createUser, String actionContent) {
       this.orderOpId = orderOpId;
       this.orderMId = orderMId;
       this.msisdn = msisdn;
       this.actionType = actionType;
       this.executeTime = executeTime;
       this.processResult = processResult;
       this.problemReason = problemReason;
       this.createDate = createDate;
       this.createUser = createUser;
       this.actionContent = actionContent;
    }
   
     @Id 

    
    @Column(name="ORDER_OP_ID", unique=true, nullable=false, length=36)
    public String getOrderOpId() {
        return this.orderOpId;
    }
    
    public void setOrderOpId(String orderOpId) {
        this.orderOpId = orderOpId;
    }

    
    @Column(name="ORDER_M_ID", nullable=false, length=36)
    public String getOrderMId() {
        return this.orderMId;
    }
    
    public void setOrderMId(String orderMId) {
        this.orderMId = orderMId;
    }

    
    @Column(name="MSISDN", length=50)
    public String getMsisdn() {
        return this.msisdn;
    }
    
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn;
    }

    
    @Column(name="ACTION_TYPE", nullable=false, length=10)
    public String getActionType() {
        return this.actionType;
    }
    
    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXECUTE_TIME", nullable=false, length=7)
    public Date getExecuteTime() {
        return this.executeTime;
    }
    
    public void setExecuteTime(Date executeTime) {
        this.executeTime = executeTime;
    }

    
    @Column(name="PROCESS_RESULT", length=20)
    public String getProcessResult() {
        return this.processResult;
    }
    
    public void setProcessResult(String processResult) {
        this.processResult = processResult;
    }

    
    @Column(name="PROBLEM_REASON", length=20)
    public String getProblemReason() {
        return this.problemReason;
    }
    
    public void setProblemReason(String problemReason) {
        this.problemReason = problemReason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    
    @Column(name="ACTION_CONTENT", nullable=false, length=100)
    public String getActionContent() {
        return this.actionContent;
    }
    
    public void setActionContent(String actionContent) {
        this.actionContent = actionContent;
    }




}


