package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderMainMetadata generated by hbm2java
 */
@Entity
@Table(name="ORDER_MAIN_METADATA")
public class OrderMainMetadata  implements java.io.Serializable {


     private String poolKey;
     private String sourceOrderId;
     private String teamGroup;
     private String sourceSysId;
     private String sourceProdTypeId;
     private String operateType;
     private String criticalFlag;
     private Date sourceCreateTime;
     private String msisdn;
     private String custName;
     private String imgIdApid;
     private String partentOrderId;
     private BigDecimal counts;
     private Date expectProcessTime;
     private Date custSpecifyDate;
     private String custId;
     private String salesId;
     private String ivrCode;
     private String promotionId;
     private String imgStorePath;
     private String imgStoreServer;
     private String cid;
     private String status;
     private String processUser;
     private String sysSyncBatchNo;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public OrderMainMetadata() {
    }

	
    public OrderMainMetadata(String poolKey, String sourceOrderId, String teamGroup, String sourceSysId, String criticalFlag, Date sourceCreateTime, BigDecimal counts, Date expectProcessTime, Date createDate, String createUser) {
        this.poolKey = poolKey;
        this.sourceOrderId = sourceOrderId;
        this.teamGroup = teamGroup;
        this.sourceSysId = sourceSysId;
        this.criticalFlag = criticalFlag;
        this.sourceCreateTime = sourceCreateTime;
        this.counts = counts;
        this.expectProcessTime = expectProcessTime;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public OrderMainMetadata(String poolKey, String sourceOrderId, String teamGroup, String sourceSysId, String sourceProdTypeId, String operateType, String criticalFlag, Date sourceCreateTime, String msisdn, String custName, String imgIdApid, String partentOrderId, BigDecimal counts, Date expectProcessTime, Date custSpecifyDate, String custId, String salesId, String ivrCode, String promotionId, String imgStorePath, String imgStoreServer, String cid, String status, String processUser, String sysSyncBatchNo, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.poolKey = poolKey;
       this.sourceOrderId = sourceOrderId;
       this.teamGroup = teamGroup;
       this.sourceSysId = sourceSysId;
       this.sourceProdTypeId = sourceProdTypeId;
       this.operateType = operateType;
       this.criticalFlag = criticalFlag;
       this.sourceCreateTime = sourceCreateTime;
       this.msisdn = msisdn;
       this.custName = custName;
       this.imgIdApid = imgIdApid;
       this.partentOrderId = partentOrderId;
       this.counts = counts;
       this.expectProcessTime = expectProcessTime;
       this.custSpecifyDate = custSpecifyDate;
       this.custId = custId;
       this.salesId = salesId;
       this.ivrCode = ivrCode;
       this.promotionId = promotionId;
       this.imgStorePath = imgStorePath;
       this.imgStoreServer = imgStoreServer;
       this.cid = cid;
       this.status = status;
       this.processUser = processUser;
       this.sysSyncBatchNo = sysSyncBatchNo;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id 

    
    @Column(name="POOL_KEY", unique=true, nullable=false, length=36)
    public String getPoolKey() {
        return this.poolKey;
    }
    
    public void setPoolKey(String poolKey) {
        this.poolKey = poolKey;
    }

    
    @Column(name="SOURCE_ORDER_ID", nullable=false, length=50)
    public String getSourceOrderId() {
        return this.sourceOrderId;
    }
    
    public void setSourceOrderId(String sourceOrderId) {
        this.sourceOrderId = sourceOrderId;
    }

    
    @Column(name="TEAM_GROUP", nullable=false, length=5)
    public String getTeamGroup() {
        return this.teamGroup;
    }
    
    public void setTeamGroup(String teamGroup) {
        this.teamGroup = teamGroup;
    }

    
    @Column(name="SOURCE_SYS_ID", nullable=false, length=20)
    public String getSourceSysId() {
        return this.sourceSysId;
    }
    
    public void setSourceSysId(String sourceSysId) {
        this.sourceSysId = sourceSysId;
    }

    
    @Column(name="SOURCE_PROD_TYPE_ID", length=50)
    public String getSourceProdTypeId() {
        return this.sourceProdTypeId;
    }
    
    public void setSourceProdTypeId(String sourceProdTypeId) {
        this.sourceProdTypeId = sourceProdTypeId;
    }

    
    @Column(name="OPERATE_TYPE", length=100)
    public String getOperateType() {
        return this.operateType;
    }
    
    public void setOperateType(String operateType) {
        this.operateType = operateType;
    }

    
    @Column(name="CRITICAL_FLAG", nullable=false, length=36)
    public String getCriticalFlag() {
        return this.criticalFlag;
    }
    
    public void setCriticalFlag(String criticalFlag) {
        this.criticalFlag = criticalFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SOURCE_CREATE_TIME", nullable=false, length=7)
    public Date getSourceCreateTime() {
        return this.sourceCreateTime;
    }
    
    public void setSourceCreateTime(Date sourceCreateTime) {
        this.sourceCreateTime = sourceCreateTime;
    }

    
    @Column(name="MSISDN", length=50)
    public String getMsisdn() {
        return this.msisdn;
    }
    
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn;
    }

    
    @Column(name="CUST_NAME", length=100)
    public String getCustName() {
        return this.custName;
    }
    
    public void setCustName(String custName) {
        this.custName = custName;
    }

    
    @Column(name="IMG_ID_APID", length=50)
    public String getImgIdApid() {
        return this.imgIdApid;
    }
    
    public void setImgIdApid(String imgIdApid) {
        this.imgIdApid = imgIdApid;
    }

    
    @Column(name="PARTENT_ORDER_ID", length=50)
    public String getPartentOrderId() {
        return this.partentOrderId;
    }
    
    public void setPartentOrderId(String partentOrderId) {
        this.partentOrderId = partentOrderId;
    }

    
    @Column(name="COUNTS", nullable=false, precision=4, scale=1)
    public BigDecimal getCounts() {
        return this.counts;
    }
    
    public void setCounts(BigDecimal counts) {
        this.counts = counts;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPECT_PROCESS_TIME", nullable=false, length=7)
    public Date getExpectProcessTime() {
        return this.expectProcessTime;
    }
    
    public void setExpectProcessTime(Date expectProcessTime) {
        this.expectProcessTime = expectProcessTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CUST_SPECIFY_DATE", length=7)
    public Date getCustSpecifyDate() {
        return this.custSpecifyDate;
    }
    
    public void setCustSpecifyDate(Date custSpecifyDate) {
        this.custSpecifyDate = custSpecifyDate;
    }

    
    @Column(name="CUST_ID", length=40)
    public String getCustId() {
        return this.custId;
    }
    
    public void setCustId(String custId) {
        this.custId = custId;
    }

    
    @Column(name="SALES_ID", length=20)
    public String getSalesId() {
        return this.salesId;
    }
    
    public void setSalesId(String salesId) {
        this.salesId = salesId;
    }

    
    @Column(name="IVR_CODE", length=40)
    public String getIvrCode() {
        return this.ivrCode;
    }
    
    public void setIvrCode(String ivrCode) {
        this.ivrCode = ivrCode;
    }

    
    @Column(name="PROMOTION_ID", length=50)
    public String getPromotionId() {
        return this.promotionId;
    }
    
    public void setPromotionId(String promotionId) {
        this.promotionId = promotionId;
    }

    
    @Column(name="IMG_STORE_PATH", length=500)
    public String getImgStorePath() {
        return this.imgStorePath;
    }
    
    public void setImgStorePath(String imgStorePath) {
        this.imgStorePath = imgStorePath;
    }

    
    @Column(name="IMG_STORE_SERVER", length=200)
    public String getImgStoreServer() {
        return this.imgStoreServer;
    }
    
    public void setImgStoreServer(String imgStoreServer) {
        this.imgStoreServer = imgStoreServer;
    }

    
    @Column(name="CID", length=50)
    public String getCid() {
        return this.cid;
    }
    
    public void setCid(String cid) {
        this.cid = cid;
    }

    
    @Column(name="STATUS", length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="PROCESS_USER", length=20)
    public String getProcessUser() {
        return this.processUser;
    }
    
    public void setProcessUser(String processUser) {
        this.processUser = processUser;
    }

    
    @Column(name="SYS_SYNC_BATCH_NO", length=50)
    public String getSysSyncBatchNo() {
        return this.sysSyncBatchNo;
    }
    
    public void setSysSyncBatchNo(String sysSyncBatchNo) {
        this.sysSyncBatchNo = sysSyncBatchNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


