package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/3/20 �U�� 04:08:26 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderMessage generated by hbm2java
 */
@Entity
@Table(name="ORDER_MESSAGE")
public class OrderMessage  implements java.io.Serializable {


     private String orderMId;
     private String msgContent;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public OrderMessage() {
    }

	
    public OrderMessage(String orderMId, Date createDate, String createUser) {
        this.orderMId = orderMId;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public OrderMessage(String orderMId, String msgContent, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.orderMId = orderMId;
       this.msgContent = msgContent;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id 

    
    @Column(name="ORDER_M_ID", unique=true, nullable=false, length=36)
    public String getOrderMId() {
        return this.orderMId;
    }
    
    public void setOrderMId(String orderMId) {
        this.orderMId = orderMId;
    }

    
    @Column(name="MSG_CONTENT", length=200)
    public String getMsgContent() {
        return this.msgContent;
    }
    
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


