package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderMainOsp generated by hbm2java
 */
@Entity
@Table(name="ORDER_MAIN_OSP")
public class OrderMainOsp  implements java.io.Serializable {


     private String orderMId;
     private String poolKey;
     private String sourceOrderId;
     private String teamGroup;
     private String sourceSysId;
     private String sourceProdTypeId;
     private String sourceProdTypeName;
     private String operateType;
     private String criticalFlag;
     private Date sourceCreateTime;
     private Date ospCreateTime;
     private String msisdn;
     private String custName;
     private String imgIdApid;
     private String partentOrderId;
     private BigDecimal counts;
     private Date expectProcessTime;
     private Date expectCompleteTime;
     private Date custSpecifyDate;
     private String custId;
     private String salesId;
     private String ivrCode;
     private String promotionId;
     private String imgStorePath;
     private String imgStoreServer;
     private String cid;
     private String processUserId;
     private String processUserName;
     private String orderTypeId;
     private String orderTypeName;
     private String orderStatus;
     private String processResult;
     private String processReason;
     private String flowId;
     private String commment;
     private String isNoticeSales;
     private String custType;
     private String corpPicTaxid;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public OrderMainOsp() {
    }

	
    public OrderMainOsp(String orderMId, String poolKey, String sourceOrderId, String teamGroup, String sourceSysId, String criticalFlag, Date sourceCreateTime, BigDecimal counts, Date expectProcessTime, Date expectCompleteTime, String orderTypeId, String orderTypeName, String orderStatus, String flowId, String isNoticeSales, Date createDate, String createUser, String custType, String corpPicTaxid) {
        this.orderMId = orderMId;
        this.poolKey = poolKey;
        this.sourceOrderId = sourceOrderId;
        this.teamGroup = teamGroup;
        this.sourceSysId = sourceSysId;
        this.criticalFlag = criticalFlag;
        this.sourceCreateTime = sourceCreateTime;
        this.counts = counts;
        this.expectProcessTime = expectProcessTime;
        this.expectCompleteTime = expectCompleteTime;
        this.orderTypeId = orderTypeId;
        this.orderTypeName = orderTypeName;
        this.orderStatus = orderStatus;
        this.flowId = flowId;
        this.isNoticeSales = isNoticeSales;
        this.createDate = createDate;
        this.createUser = createUser;
        this.custType = custType;
        this.corpPicTaxid = corpPicTaxid;
    }
    public OrderMainOsp(String orderMId, String poolKey, String sourceOrderId, String teamGroup, String sourceSysId, String sourceProdTypeId, String sourceProdTypeName, String operateType, String criticalFlag, Date sourceCreateTime, Date ospCreateTime, String msisdn, String custName, String imgIdApid, String partentOrderId, BigDecimal counts, Date expectProcessTime, Date expectCompleteTime, Date custSpecifyDate, String custId, String salesId, String ivrCode, String promotionId, String imgStorePath, String imgStoreServer, String cid, String processUserId, String processUserName, String orderTypeId, String orderTypeName, String orderStatus, String processResult, String processReason, String flowId, String commment, String isNoticeSales, Date createDate, String createUser, Date updateDate, String updateUser, String custType, String corpPicTaxid) {
       this.orderMId = orderMId;
       this.poolKey = poolKey;
       this.sourceOrderId = sourceOrderId;
       this.teamGroup = teamGroup;
       this.sourceSysId = sourceSysId;
       this.sourceProdTypeId = sourceProdTypeId;
       this.sourceProdTypeName = sourceProdTypeName;
       this.operateType = operateType;
       this.criticalFlag = criticalFlag;
       this.sourceCreateTime = sourceCreateTime;
       this.ospCreateTime = ospCreateTime;
       this.msisdn = msisdn;
       this.custName = custName;
       this.imgIdApid = imgIdApid;
       this.partentOrderId = partentOrderId;
       this.counts = counts;
       this.expectProcessTime = expectProcessTime;
       this.expectCompleteTime = expectCompleteTime;
       this.custSpecifyDate = custSpecifyDate;
       this.custId = custId;
       this.salesId = salesId;
       this.ivrCode = ivrCode;
       this.promotionId = promotionId;
       this.imgStorePath = imgStorePath;
       this.imgStoreServer = imgStoreServer;
       this.cid = cid;
       this.processUserId = processUserId;
       this.processUserName = processUserName;
       this.orderTypeId = orderTypeId;
       this.orderTypeName = orderTypeName;
       this.orderStatus = orderStatus;
       this.processResult = processResult;
       this.processReason = processReason;
       this.flowId = flowId;
       this.commment = commment;
       this.isNoticeSales = isNoticeSales;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.custType = custType;
       this.corpPicTaxid = corpPicTaxid;
    }
   
     @Id 

    
    @Column(name="ORDER_M_ID", unique=true, nullable=false, length=36)
    public String getOrderMId() {
        return this.orderMId;
    }
    
    public void setOrderMId(String orderMId) {
        this.orderMId = orderMId;
    }

    
    @Column(name="POOL_KEY", nullable=false, length=36)
    public String getPoolKey() {
        return this.poolKey;
    }
    
    public void setPoolKey(String poolKey) {
        this.poolKey = poolKey;
    }

    
    @Column(name="SOURCE_ORDER_ID", nullable=false, length=50)
    public String getSourceOrderId() {
        return this.sourceOrderId;
    }
    
    public void setSourceOrderId(String sourceOrderId) {
        this.sourceOrderId = sourceOrderId;
    }

    
    @Column(name="TEAM_GROUP", nullable=false, length=5)
    public String getTeamGroup() {
        return this.teamGroup;
    }
    
    public void setTeamGroup(String teamGroup) {
        this.teamGroup = teamGroup;
    }

    
    @Column(name="SOURCE_SYS_ID", nullable=false, length=20)
    public String getSourceSysId() {
        return this.sourceSysId;
    }
    
    public void setSourceSysId(String sourceSysId) {
        this.sourceSysId = sourceSysId;
    }

    
    @Column(name="SOURCE_PROD_TYPE_ID", length=50)
    public String getSourceProdTypeId() {
        return this.sourceProdTypeId;
    }
    
    public void setSourceProdTypeId(String sourceProdTypeId) {
        this.sourceProdTypeId = sourceProdTypeId;
    }

    
    @Column(name="SOURCE_PROD_TYPE_NAME", length=100)
    public String getSourceProdTypeName() {
        return this.sourceProdTypeName;
    }
    
    public void setSourceProdTypeName(String sourceProdTypeName) {
        this.sourceProdTypeName = sourceProdTypeName;
    }

    
    @Column(name="OPERATE_TYPE", length=100)
    public String getOperateType() {
        return this.operateType;
    }
    
    public void setOperateType(String operateType) {
        this.operateType = operateType;
    }

    
    @Column(name="CRITICAL_FLAG", nullable=false, length=36)
    public String getCriticalFlag() {
        return this.criticalFlag;
    }
    
    public void setCriticalFlag(String criticalFlag) {
        this.criticalFlag = criticalFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SOURCE_CREATE_TIME", nullable=false, length=7)
    public Date getSourceCreateTime() {
        return this.sourceCreateTime;
    }
    
    public void setSourceCreateTime(Date sourceCreateTime) {
        this.sourceCreateTime = sourceCreateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OSP_CREATE_TIME", length=7)
    public Date getOspCreateTime() {
        return this.ospCreateTime;
    }
    
    public void setOspCreateTime(Date ospCreateTime) {
        this.ospCreateTime = ospCreateTime;
    }

    
    @Column(name="MSISDN", length=50)
    public String getMsisdn() {
        return this.msisdn;
    }
    
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn;
    }

    
    @Column(name="CUST_NAME", length=100)
    public String getCustName() {
        return this.custName;
    }
    
    public void setCustName(String custName) {
        this.custName = custName;
    }

    
    @Column(name="IMG_ID_APID", length=50)
    public String getImgIdApid() {
        return this.imgIdApid;
    }
    
    public void setImgIdApid(String imgIdApid) {
        this.imgIdApid = imgIdApid;
    }

    
    @Column(name="PARTENT_ORDER_ID", length=50)
    public String getPartentOrderId() {
        return this.partentOrderId;
    }
    
    public void setPartentOrderId(String partentOrderId) {
        this.partentOrderId = partentOrderId;
    }

    
    @Column(name="COUNTS", nullable=false, precision=4, scale=1)
    public BigDecimal getCounts() {
        return this.counts;
    }
    
    public void setCounts(BigDecimal counts) {
        this.counts = counts;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPECT_PROCESS_TIME", nullable=false, length=7)
    public Date getExpectProcessTime() {
        return this.expectProcessTime;
    }
    
    public void setExpectProcessTime(Date expectProcessTime) {
        this.expectProcessTime = expectProcessTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPECT_COMPLETE_TIME", nullable=false, length=7)
    public Date getExpectCompleteTime() {
        return this.expectCompleteTime;
    }
    
    public void setExpectCompleteTime(Date expectCompleteTime) {
        this.expectCompleteTime = expectCompleteTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CUST_SPECIFY_DATE", length=7)
    public Date getCustSpecifyDate() {
        return this.custSpecifyDate;
    }
    
    public void setCustSpecifyDate(Date custSpecifyDate) {
        this.custSpecifyDate = custSpecifyDate;
    }

    
    @Column(name="CUST_ID", length=40)
    public String getCustId() {
        return this.custId;
    }
    
    public void setCustId(String custId) {
        this.custId = custId;
    }

    
    @Column(name="SALES_ID", length=20)
    public String getSalesId() {
        return this.salesId;
    }
    
    public void setSalesId(String salesId) {
        this.salesId = salesId;
    }

    
    @Column(name="IVR_CODE", length=40)
    public String getIvrCode() {
        return this.ivrCode;
    }
    
    public void setIvrCode(String ivrCode) {
        this.ivrCode = ivrCode;
    }

    
    @Column(name="PROMOTION_ID", length=50)
    public String getPromotionId() {
        return this.promotionId;
    }
    
    public void setPromotionId(String promotionId) {
        this.promotionId = promotionId;
    }

    
    @Column(name="IMG_STORE_PATH", length=500)
    public String getImgStorePath() {
        return this.imgStorePath;
    }
    
    public void setImgStorePath(String imgStorePath) {
        this.imgStorePath = imgStorePath;
    }

    
    @Column(name="IMG_STORE_SERVER", length=200)
    public String getImgStoreServer() {
        return this.imgStoreServer;
    }
    
    public void setImgStoreServer(String imgStoreServer) {
        this.imgStoreServer = imgStoreServer;
    }

    
    @Column(name="CID", length=50)
    public String getCid() {
        return this.cid;
    }
    
    public void setCid(String cid) {
        this.cid = cid;
    }

    
    @Column(name="PROCESS_USER_ID", length=20)
    public String getProcessUserId() {
        return this.processUserId;
    }
    
    public void setProcessUserId(String processUserId) {
        this.processUserId = processUserId;
    }

    
    @Column(name="PROCESS_USER_NAME", length=50)
    public String getProcessUserName() {
        return this.processUserName;
    }
    
    public void setProcessUserName(String processUserName) {
        this.processUserName = processUserName;
    }

    
    @Column(name="ORDER_TYPE_ID", nullable=false, length=40)
    public String getOrderTypeId() {
        return this.orderTypeId;
    }
    
    public void setOrderTypeId(String orderTypeId) {
        this.orderTypeId = orderTypeId;
    }

    
    @Column(name="ORDER_TYPE_NAME", nullable=false, length=100)
    public String getOrderTypeName() {
        return this.orderTypeName;
    }
    
    public void setOrderTypeName(String orderTypeName) {
        this.orderTypeName = orderTypeName;
    }

    
    @Column(name="ORDER_STATUS", nullable=false, length=10)
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    
    @Column(name="PROCESS_RESULT", length=10)
    public String getProcessResult() {
        return this.processResult;
    }
    
    public void setProcessResult(String processResult) {
        this.processResult = processResult;
    }

    
    @Column(name="PROCESS_REASON", length=10)
    public String getProcessReason() {
        return this.processReason;
    }
    
    public void setProcessReason(String processReason) {
        this.processReason = processReason;
    }

    
    @Column(name="FLOW_ID", nullable=false, length=40)
    public String getFlowId() {
        return this.flowId;
    }
    
    public void setFlowId(String flowId) {
        this.flowId = flowId;
    }

    
    @Column(name="COMMMENT", length=500)
    public String getCommment() {
        return this.commment;
    }
    
    public void setCommment(String commment) {
        this.commment = commment;
    }

    
    @Column(name="IS_NOTICE_SALES", nullable=false, length=5)
    public String getIsNoticeSales() {
        return this.isNoticeSales;
    }
    
    public void setIsNoticeSales(String isNoticeSales) {
        this.isNoticeSales = isNoticeSales;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    @Column(name="CUST_TYPE", nullable=true, length=10)
	public String getCustType() {
		return custType;
	}


	public void setCustType(String custType) {
		this.custType = custType;
	}

    @Column(name="CORP_PIC_TAXID", nullable=true, length=20)
	public String getCorpPicTaxid() {
		return corpPicTaxid;
	}

	public void setCorpPicTaxid(String corpPicTaxid) {
		this.corpPicTaxid = corpPicTaxid;
	}




}


