package com.fet.crm.osp.platform.core.db.model;
// Generated May 10, 2017 12:50:51 AM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderKpiOwnerId generated by hbm2java
 */
@Embeddable
public class OrderKpiOwnerId  implements java.io.Serializable {


     private String orderMId;
     private String kpiOwnerId;

    public OrderKpiOwnerId() {
    }

    public OrderKpiOwnerId(String orderMId, String kpiOwnerId) {
       this.orderMId = orderMId;
       this.kpiOwnerId = kpiOwnerId;
    }
   


    @Column(name="ORDER_M_ID", nullable=false, length=36)
    public String getOrderMId() {
        return this.orderMId;
    }
    
    public void setOrderMId(String orderMId) {
        this.orderMId = orderMId;
    }


    @Column(name="KPI_OWNER_ID", nullable=false, length=20)
    public String getKpiOwnerId() {
        return this.kpiOwnerId;
    }
    
    public void setKpiOwnerId(String kpiOwnerId) {
        this.kpiOwnerId = kpiOwnerId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderKpiOwnerId) ) return false;
		 OrderKpiOwnerId castOther = ( OrderKpiOwnerId ) other; 
         
		 return ( (this.getOrderMId()==castOther.getOrderMId()) || ( this.getOrderMId()!=null && castOther.getOrderMId()!=null && this.getOrderMId().equals(castOther.getOrderMId()) ) )
 && ( (this.getKpiOwnerId()==castOther.getKpiOwnerId()) || ( this.getKpiOwnerId()!=null && castOther.getKpiOwnerId()!=null && this.getKpiOwnerId().equals(castOther.getKpiOwnerId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOrderMId() == null ? 0 : this.getOrderMId().hashCode() );
         result = 37 * result + ( getKpiOwnerId() == null ? 0 : this.getKpiOwnerId().hashCode() );
         return result;
   }   


}


