package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/5/18 下午 05:26:30 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderDispatchNotifyId generated by hbm2java
 */
@Embeddable
public class OrderDispatchNotifyId  implements java.io.Serializable {


     private String batchNo;
     private String orderMId;

    public OrderDispatchNotifyId() {
    }

    public OrderDispatchNotifyId(String batchNo, String orderMId) {
       this.batchNo = batchNo;
       this.orderMId = orderMId;
    }
   


    @Column(name="BATCH_NO", nullable=false, length=36)
    public String getBatchNo() {
        return this.batchNo;
    }
    
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }


    @Column(name="ORDER_M_ID", nullable=false, length=36)
    public String getOrderMId() {
        return this.orderMId;
    }
    
    public void setOrderMId(String orderMId) {
        this.orderMId = orderMId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderDispatchNotifyId) ) return false;
		 OrderDispatchNotifyId castOther = ( OrderDispatchNotifyId ) other; 
         
		 return ( (this.getBatchNo()==castOther.getBatchNo()) || ( this.getBatchNo()!=null && castOther.getBatchNo()!=null && this.getBatchNo().equals(castOther.getBatchNo()) ) )
 && ( (this.getOrderMId()==castOther.getOrderMId()) || ( this.getOrderMId()!=null && castOther.getOrderMId()!=null && this.getOrderMId().equals(castOther.getOrderMId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBatchNo() == null ? 0 : this.getBatchNo().hashCode() );
         result = 37 * result + ( getOrderMId() == null ? 0 : this.getOrderMId().hashCode() );
         return result;
   }   


}


