package com.fet.crm.osp.platform.core.db.model;
// Generated May 10, 2017 11:30:49 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefStaff generated by hbm2java
 */
@Entity
@Table(name="REF_STAFF")
public class RefStaff  implements java.io.Serializable {


     private RefStaffId id;
     private String empname;
     private String engname;
     private String aliasname;
     private String email;
     private String headEmpno;
     private String headEmpname;
     private String headEmail;
     private Date createDate;
     private String createUser;

    public RefStaff() {
    }

	
    public RefStaff(RefStaffId id, Date createDate) {
        this.id = id;
        this.createDate = createDate;
    }
    public RefStaff(RefStaffId id, String empname, String engname, String aliasname, String email, String headEmpno, String headEmpname, String headEmail, Date createDate, String createUser) {
       this.id = id;
       this.empname = empname;
       this.engname = engname;
       this.aliasname = aliasname;
       this.email = email;
       this.headEmpno = headEmpno;
       this.headEmpname = headEmpname;
       this.headEmail = headEmail;
       this.createDate = createDate;
       this.createUser = createUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="empno", column=@Column(name="EMPNO", nullable=false, length=10) ), 
        @AttributeOverride(name="deptcode", column=@Column(name="DEPTCODE", nullable=false, length=40) ) } )
    public RefStaffId getId() {
        return this.id;
    }
    
    public void setId(RefStaffId id) {
        this.id = id;
    }

    
    @Column(name="EMPNAME", length=30)
    public String getEmpname() {
        return this.empname;
    }
    
    public void setEmpname(String empname) {
        this.empname = empname;
    }

    
    @Column(name="ENGNAME", length=40)
    public String getEngname() {
        return this.engname;
    }
    
    public void setEngname(String engname) {
        this.engname = engname;
    }

    
    @Column(name="ALIASNAME", length=40)
    public String getAliasname() {
        return this.aliasname;
    }
    
    public void setAliasname(String aliasname) {
        this.aliasname = aliasname;
    }

    
    @Column(name="EMAIL", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="HEAD_EMPNO", length=10)
    public String getHeadEmpno() {
        return this.headEmpno;
    }
    
    public void setHeadEmpno(String headEmpno) {
        this.headEmpno = headEmpno;
    }

    
    @Column(name="HEAD_EMPNAME", length=30)
    public String getHeadEmpname() {
        return this.headEmpname;
    }
    
    public void setHeadEmpname(String headEmpname) {
        this.headEmpname = headEmpname;
    }

    
    @Column(name="HEAD_EMAIL", length=100)
    public String getHeadEmail() {
        return this.headEmail;
    }
    
    public void setHeadEmail(String headEmail) {
        this.headEmail = headEmail;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", length=12)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }




}


