package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/5/5 ¤W¤È 09:41:50 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysActionLogId generated by hbm2java
 */
@Embeddable
public class SysActionLogId  implements java.io.Serializable {


     private String requestId;
     private String logId;

    public SysActionLogId() {
    }

    public SysActionLogId(String requestId, String logId) {
       this.requestId = requestId;
       this.logId = logId;
    }
   


    @Column(name="REQUEST_ID", nullable=false, length=36)
    public String getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }


    @Column(name="LOG_ID", nullable=false, length=36)
    public String getLogId() {
        return this.logId;
    }
    
    public void setLogId(String logId) {
        this.logId = logId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysActionLogId) ) return false;
		 SysActionLogId castOther = ( SysActionLogId ) other; 
         
		 return ( (this.getRequestId()==castOther.getRequestId()) || ( this.getRequestId()!=null && castOther.getRequestId()!=null && this.getRequestId().equals(castOther.getRequestId()) ) )
 && ( (this.getLogId()==castOther.getLogId()) || ( this.getLogId()!=null && castOther.getLogId()!=null && this.getLogId().equals(castOther.getLogId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRequestId() == null ? 0 : this.getRequestId().hashCode() );
         result = 37 * result + ( getLogId() == null ? 0 : this.getLogId().hashCode() );
         return result;
   }   


}


