package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysFlowSourceMap generated by hbm2java
 */
@Entity
@Table(name="SYS_FLOW_SOURCE_MAP")
public class SysFlowSourceMap  implements java.io.Serializable {


     private SysFlowSourceMapId id;
     private BigDecimal upperLimitCounts;
     private BigDecimal lowerLimitCounts;
     private String orderTypeId;
     private String orderTypeName;
     private String isDefault;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public SysFlowSourceMap() {
    }

	
    public SysFlowSourceMap(SysFlowSourceMapId id, BigDecimal upperLimitCounts, BigDecimal lowerLimitCounts, String orderTypeId, String isDefault, Date createDate, String createUser) {
        this.id = id;
        this.upperLimitCounts = upperLimitCounts;
        this.lowerLimitCounts = lowerLimitCounts;
        this.orderTypeId = orderTypeId;
        this.isDefault = isDefault;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public SysFlowSourceMap(SysFlowSourceMapId id, BigDecimal upperLimitCounts, BigDecimal lowerLimitCounts, String orderTypeId, String orderTypeName, String isDefault, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.id = id;
       this.upperLimitCounts = upperLimitCounts;
       this.lowerLimitCounts = lowerLimitCounts;
       this.orderTypeId = orderTypeId;
       this.orderTypeName = orderTypeName;
       this.isDefault = isDefault;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sourceSysId", column=@Column(name="SOURCE_SYS_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="flowId", column=@Column(name="FLOW_ID", nullable=false, length=40) ), 
        @AttributeOverride(name="sourceProdTypeId", column=@Column(name="SOURCE_PROD_TYPE_ID", nullable=false, length=50) ) } )
    public SysFlowSourceMapId getId() {
        return this.id;
    }
    
    public void setId(SysFlowSourceMapId id) {
        this.id = id;
    }

    
    @Column(name="UPPER_LIMIT_COUNTS", nullable=false, precision=4, scale=1)
    public BigDecimal getUpperLimitCounts() {
        return this.upperLimitCounts;
    }
    
    public void setUpperLimitCounts(BigDecimal upperLimitCounts) {
        this.upperLimitCounts = upperLimitCounts;
    }

    
    @Column(name="LOWER_LIMIT_COUNTS", nullable=false, precision=4, scale=1)
    public BigDecimal getLowerLimitCounts() {
        return this.lowerLimitCounts;
    }
    
    public void setLowerLimitCounts(BigDecimal lowerLimitCounts) {
        this.lowerLimitCounts = lowerLimitCounts;
    }

    
    @Column(name="ORDER_TYPE_ID", nullable=false, length=50)
    public String getOrderTypeId() {
        return this.orderTypeId;
    }
    
    public void setOrderTypeId(String orderTypeId) {
        this.orderTypeId = orderTypeId;
    }

    
    @Column(name="ORDER_TYPE_NAME", length=50)
    public String getOrderTypeName() {
        return this.orderTypeName;
    }
    
    public void setOrderTypeName(String orderTypeName) {
        this.orderTypeName = orderTypeName;
    }

    
    @Column(name="IS_DEFAULT", nullable=false, length=5)
    public String getIsDefault() {
        return this.isDefault;
    }
    
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


