package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysGlobalConfig generated by hbm2java
 */
@Entity
@Table(name="SYS_GLOBAL_CONFIG")
public class SysGlobalConfig  implements java.io.Serializable {


     private String confId;
     private String confValue;
     private String description;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public SysGlobalConfig() {
    }

	
    public SysGlobalConfig(String confId, String confValue, Date createDate, String createUser) {
        this.confId = confId;
        this.confValue = confValue;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public SysGlobalConfig(String confId, String confValue, String description, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.confId = confId;
       this.confValue = confValue;
       this.description = description;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id 

    
    @Column(name="CONF_ID", unique=true, nullable=false, length=100)
    public String getConfId() {
        return this.confId;
    }
    
    public void setConfId(String confId) {
        this.confId = confId;
    }

    
    @Column(name="CONF_VALUE", nullable=false, length=500)
    public String getConfValue() {
        return this.confValue;
    }
    
    public void setConfValue(String confValue) {
        this.confValue = confValue;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


