package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/5/2 �U�� 07:01:42 by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysMenu generated by hbm2java
 */
@Entity
@Table(name="SYS_MENU")
public class SysMenu  implements java.io.Serializable {


     private String menuId;
     private String skillId;
     private BigDecimal sortSequence;
     private String menuText;
     private String menuType;
     private String menuOpenType;
     private String menuLev;
     private String menuPartent;
     private String menuLink;
     private String active;
     private String description;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private String menuIcon;

    public SysMenu() {
    }

	
    public SysMenu(String menuId, BigDecimal sortSequence, String menuText, String menuType, String active, Date createDate, String createUser) {
        this.menuId = menuId;
        this.sortSequence = sortSequence;
        this.menuText = menuText;
        this.menuType = menuType;
        this.active = active;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public SysMenu(String menuId, String skillId, BigDecimal sortSequence, String menuText, String menuType, String menuOpenType, String menuLev, String menuPartent, String menuLink, String active, String description, Date createDate, String createUser, Date updateDate, String updateUser, String menuIcon) {
       this.menuId = menuId;
       this.skillId = skillId;
       this.sortSequence = sortSequence;
       this.menuText = menuText;
       this.menuType = menuType;
       this.menuOpenType = menuOpenType;
       this.menuLev = menuLev;
       this.menuPartent = menuPartent;
       this.menuLink = menuLink;
       this.active = active;
       this.description = description;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.menuIcon = menuIcon;
    }
   
     @Id 

    
    @Column(name="MENU_ID", unique=true, nullable=false, length=40)
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    
    @Column(name="SKILL_ID", length=40)
    public String getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(String skillId) {
        this.skillId = skillId;
    }

    
    @Column(name="SORT_SEQUENCE", nullable=false, precision=4, scale=1)
    public BigDecimal getSortSequence() {
        return this.sortSequence;
    }
    
    public void setSortSequence(BigDecimal sortSequence) {
        this.sortSequence = sortSequence;
    }

    
    @Column(name="MENU_TEXT", nullable=false, length=50)
    public String getMenuText() {
        return this.menuText;
    }
    
    public void setMenuText(String menuText) {
        this.menuText = menuText;
    }

    
    @Column(name="MENU_TYPE", nullable=false, length=5)
    public String getMenuType() {
        return this.menuType;
    }
    
    public void setMenuType(String menuType) {
        this.menuType = menuType;
    }

    
    @Column(name="MENU_OPEN_TYPE", length=5)
    public String getMenuOpenType() {
        return this.menuOpenType;
    }
    
    public void setMenuOpenType(String menuOpenType) {
        this.menuOpenType = menuOpenType;
    }

    
    @Column(name="MENU_LEV", length=5)
    public String getMenuLev() {
        return this.menuLev;
    }
    
    public void setMenuLev(String menuLev) {
        this.menuLev = menuLev;
    }

    
    @Column(name="MENU_PARTENT", length=40)
    public String getMenuPartent() {
        return this.menuPartent;
    }
    
    public void setMenuPartent(String menuPartent) {
        this.menuPartent = menuPartent;
    }

    
    @Column(name="MENU_LINK", length=500)
    public String getMenuLink() {
        return this.menuLink;
    }
    
    public void setMenuLink(String menuLink) {
        this.menuLink = menuLink;
    }

    
    @Column(name="ACTIVE", nullable=false, length=5)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    
    @Column(name="MENU_ICON", length=20)
    public String getMenuIcon() {
        return this.menuIcon;
    }
    
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }




}


