package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/3/8 下午 05:47:19 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysNotification generated by hbm2java
 */
@Entity
@Table(name="SYS_NOTIFICATION")
public class SysNotification  implements java.io.Serializable {


     private String notifyId;
     private String notifyType;
     private String orderMId;
     private String emailRecipients;
     private String emailCpRecipients;
     private String smsRecipients;
     private String hasSend;
     private String subject;
     private String content;
     private Date sendDate;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public SysNotification() {
    }

	
    public SysNotification(String notifyId, String notifyType, String orderMId, String hasSend, Date createDate, String createUser) {
        this.notifyId = notifyId;
        this.notifyType = notifyType;
        this.orderMId = orderMId;
        this.hasSend = hasSend;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public SysNotification(String notifyId, String notifyType, String orderMId, String emailRecipients, String emailCpRecipients, String smsRecipients, String hasSend, String subject, String content, Date sendDate, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.notifyId = notifyId;
       this.notifyType = notifyType;
       this.orderMId = orderMId;
       this.emailRecipients = emailRecipients;
       this.emailCpRecipients = emailCpRecipients;
       this.smsRecipients = smsRecipients;
       this.hasSend = hasSend;
       this.subject = subject;
       this.content = content;
       this.sendDate = sendDate;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id 

    
    @Column(name="NOTIFY_ID", unique=true, nullable=false, length=36)
    public String getNotifyId() {
        return this.notifyId;
    }
    
    public void setNotifyId(String notifyId) {
        this.notifyId = notifyId;
    }

    
    @Column(name="NOTIFY_TYPE", nullable=false, length=50)
    public String getNotifyType() {
        return this.notifyType;
    }
    
    public void setNotifyType(String notifyType) {
        this.notifyType = notifyType;
    }

    
    @Column(name="ORDER_M_ID", nullable=false, length=36)
    public String getOrderMId() {
        return this.orderMId;
    }
    
    public void setOrderMId(String orderMId) {
        this.orderMId = orderMId;
    }

    
    @Column(name="EMAIL_RECIPIENTS", length=2000)
    public String getEmailRecipients() {
        return this.emailRecipients;
    }
    
    public void setEmailRecipients(String emailRecipients) {
        this.emailRecipients = emailRecipients;
    }

    
    @Column(name="EMAIL_CP_RECIPIENTS", length=2000)
    public String getEmailCpRecipients() {
        return this.emailCpRecipients;
    }
    
    public void setEmailCpRecipients(String emailCpRecipients) {
        this.emailCpRecipients = emailCpRecipients;
    }

    
    @Column(name="SMS_RECIPIENTS")
    public String getSmsRecipients() {
        return this.smsRecipients;
    }
    
    public void setSmsRecipients(String smsRecipients) {
        this.smsRecipients = smsRecipients;
    }

    
    @Column(name="HAS_SEND", nullable=false, length=5)
    public String getHasSend() {
        return this.hasSend;
    }
    
    public void setHasSend(String hasSend) {
        this.hasSend = hasSend;
    }

    
    @Column(name="SUBJECT", length=50)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="CONTENT", length=3000)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SEND_DATE", length=7)
    public Date getSendDate() {
        return this.sendDate;
    }
    
    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


