package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 ¤U¤È 01:10:48 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysOptionsReferenceId generated by hbm2java
 */
@Embeddable
public class SysOptionsReferenceId  implements java.io.Serializable {


     private String optionsType;
     private String optionsValue;

    public SysOptionsReferenceId() {
    }

    public SysOptionsReferenceId(String optionsType, String optionsValue) {
       this.optionsType = optionsType;
       this.optionsValue = optionsValue;
    }
   


    @Column(name="OPTIONS_TYPE", nullable=false, length=20)
    public String getOptionsType() {
        return this.optionsType;
    }
    
    public void setOptionsType(String optionsType) {
        this.optionsType = optionsType;
    }


    @Column(name="OPTIONS_VALUE", nullable=false, length=100)
    public String getOptionsValue() {
        return this.optionsValue;
    }
    
    public void setOptionsValue(String optionsValue) {
        this.optionsValue = optionsValue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysOptionsReferenceId) ) return false;
		 SysOptionsReferenceId castOther = ( SysOptionsReferenceId ) other; 
         
		 return ( (this.getOptionsType()==castOther.getOptionsType()) || ( this.getOptionsType()!=null && castOther.getOptionsType()!=null && this.getOptionsType().equals(castOther.getOptionsType()) ) )
 && ( (this.getOptionsValue()==castOther.getOptionsValue()) || ( this.getOptionsValue()!=null && castOther.getOptionsValue()!=null && this.getOptionsValue().equals(castOther.getOptionsValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOptionsType() == null ? 0 : this.getOptionsType().hashCode() );
         result = 37 * result + ( getOptionsValue() == null ? 0 : this.getOptionsValue().hashCode() );
         return result;
   }   


}


