package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/3/8 下午 05:47:19 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysOptionsCombo generated by hbm2java
 */
@Entity
@Table(name="SYS_OPTIONS_COMBO")
public class SysOptionsCombo  implements java.io.Serializable {


     private SysOptionsComboId id;
     private String comboText;
     private String comboContent;
     private String description;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public SysOptionsCombo() {
    }

	
    public SysOptionsCombo(SysOptionsComboId id, String comboText, Date createDate, String createUser) {
        this.id = id;
        this.comboText = comboText;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public SysOptionsCombo(SysOptionsComboId id, String comboText, String comboContent, String description, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.id = id;
       this.comboText = comboText;
       this.comboContent = comboContent;
       this.description = description;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="comboType", column=@Column(name="COMBO_TYPE", nullable=false, length=20) ), 
        @AttributeOverride(name="comboValue", column=@Column(name="COMBO_VALUE", nullable=false, length=100) ) } )
    public SysOptionsComboId getId() {
        return this.id;
    }
    
    public void setId(SysOptionsComboId id) {
        this.id = id;
    }

    
    @Column(name="COMBO_TEXT", nullable=false, length=100)
    public String getComboText() {
        return this.comboText;
    }
    
    public void setComboText(String comboText) {
        this.comboText = comboText;
    }

    
    @Column(name="COMBO_CONTENT", length=500)
    public String getComboContent() {
        return this.comboContent;
    }
    
    public void setComboContent(String comboContent) {
        this.comboContent = comboContent;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


