package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/3/8 下午 05:47:19 by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysOrderTypeSetting generated by hbm2java
 */
@Entity
@Table(name="SYS_ORDER_TYPE_SETTING")
public class SysOrderTypeSetting  implements java.io.Serializable {


     private String orderTypeId;
     private String orderTypeName;
     private BigDecimal successSec;
     private BigDecimal failSec;
     private BigDecimal regularTime;
     private BigDecimal overtime;
     private BigDecimal criticalCounts;
     private BigDecimal overtimeCounts;
     private String email;
     private String btnCreateSingle;
     private String btnCreateBatch;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;
     private String btnNotice;
     private String kpiDayType;
     private String chkCreateDate;
     private String isRegularTime;
     private String beforeCreateDate;
     private String startCountTime;

    public SysOrderTypeSetting() {
    }

	
    public SysOrderTypeSetting(String orderTypeId, String orderTypeName, BigDecimal successSec, BigDecimal failSec, BigDecimal overtime, BigDecimal criticalCounts, BigDecimal overtimeCounts, String btnCreateSingle, String btnCreateBatch, Date createDate, String createUser, String btnNotice, String kpiDayType, String chkCreateDate, String isRegularTime) {
        this.orderTypeId = orderTypeId;
        this.orderTypeName = orderTypeName;
        this.successSec = successSec;
        this.failSec = failSec;
        this.overtime = overtime;
        this.criticalCounts = criticalCounts;
        this.overtimeCounts = overtimeCounts;
        this.btnCreateSingle = btnCreateSingle;
        this.btnCreateBatch = btnCreateBatch;
        this.createDate = createDate;
        this.createUser = createUser;
        this.btnNotice = btnNotice;
        this.kpiDayType = kpiDayType;
        this.chkCreateDate = chkCreateDate;
        this.isRegularTime = isRegularTime;
    }
    public SysOrderTypeSetting(String orderTypeId, String orderTypeName, BigDecimal successSec, BigDecimal failSec, BigDecimal regularTime, BigDecimal overtime, BigDecimal criticalCounts, BigDecimal overtimeCounts, String email, String btnCreateSingle, String btnCreateBatch, Date createDate, String createUser, Date updateDate, String updateUser, String btnNotice, String kpiDayType, String chkCreateDate, String isRegularTime, String beforeCreateDate, String startCountTime) {
       this.orderTypeId = orderTypeId;
       this.orderTypeName = orderTypeName;
       this.successSec = successSec;
       this.failSec = failSec;
       this.regularTime = regularTime;
       this.overtime = overtime;
       this.criticalCounts = criticalCounts;
       this.overtimeCounts = overtimeCounts;
       this.email = email;
       this.btnCreateSingle = btnCreateSingle;
       this.btnCreateBatch = btnCreateBatch;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.btnNotice = btnNotice;
       this.kpiDayType = kpiDayType;
       this.chkCreateDate = chkCreateDate;
       this.isRegularTime = isRegularTime;
       this.beforeCreateDate = beforeCreateDate;
       this.startCountTime = startCountTime;
    }
   
     @Id 

    
    @Column(name="ORDER_TYPE_ID", unique=true, nullable=false, length=40)
    public String getOrderTypeId() {
        return this.orderTypeId;
    }
    
    public void setOrderTypeId(String orderTypeId) {
        this.orderTypeId = orderTypeId;
    }

    
    @Column(name="ORDER_TYPE_NAME", nullable=false, length=50)
    public String getOrderTypeName() {
        return this.orderTypeName;
    }
    
    public void setOrderTypeName(String orderTypeName) {
        this.orderTypeName = orderTypeName;
    }

    
    @Column(name="SUCCESS_SEC", nullable=false, precision=6, scale=1)
    public BigDecimal getSuccessSec() {
        return this.successSec;
    }
    
    public void setSuccessSec(BigDecimal successSec) {
        this.successSec = successSec;
    }

    
    @Column(name="FAIL_SEC", nullable=false, precision=6, scale=1)
    public BigDecimal getFailSec() {
        return this.failSec;
    }
    
    public void setFailSec(BigDecimal failSec) {
        this.failSec = failSec;
    }

    
    @Column(name="REGULAR_TIME", precision=6, scale=1)
    public BigDecimal getRegularTime() {
        return this.regularTime;
    }
    
    public void setRegularTime(BigDecimal regularTime) {
        this.regularTime = regularTime;
    }

    
    @Column(name="OVERTIME", nullable=false, precision=6, scale=1)
    public BigDecimal getOvertime() {
        return this.overtime;
    }
    
    public void setOvertime(BigDecimal overtime) {
        this.overtime = overtime;
    }

    
    @Column(name="CRITICAL_COUNTS", nullable=false, precision=6, scale=1)
    public BigDecimal getCriticalCounts() {
        return this.criticalCounts;
    }
    
    public void setCriticalCounts(BigDecimal criticalCounts) {
        this.criticalCounts = criticalCounts;
    }

    
    @Column(name="OVERTIME_COUNTS", nullable=false, precision=6, scale=1)
    public BigDecimal getOvertimeCounts() {
        return this.overtimeCounts;
    }
    
    public void setOvertimeCounts(BigDecimal overtimeCounts) {
        this.overtimeCounts = overtimeCounts;
    }

    
    @Column(name="EMAIL", length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="BTN_CREATE_SINGLE", nullable=false, length=5)
    public String getBtnCreateSingle() {
        return this.btnCreateSingle;
    }
    
    public void setBtnCreateSingle(String btnCreateSingle) {
        this.btnCreateSingle = btnCreateSingle;
    }

    
    @Column(name="BTN_CREATE_BATCH", nullable=false, length=5)
    public String getBtnCreateBatch() {
        return this.btnCreateBatch;
    }
    
    public void setBtnCreateBatch(String btnCreateBatch) {
        this.btnCreateBatch = btnCreateBatch;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    
    @Column(name="BTN_NOTICE", nullable=false, length=5)
    public String getBtnNotice() {
        return this.btnNotice;
    }
    
    public void setBtnNotice(String btnNotice) {
        this.btnNotice = btnNotice;
    }

    
    @Column(name="KPI_DAY_TYPE", nullable=false, length=100)
    public String getKpiDayType() {
        return this.kpiDayType;
    }
    
    public void setKpiDayType(String kpiDayType) {
        this.kpiDayType = kpiDayType;
    }

    
    @Column(name="CHK_CREATE_DATE", nullable=false, length=5)
    public String getChkCreateDate() {
        return this.chkCreateDate;
    }
    
    public void setChkCreateDate(String chkCreateDate) {
        this.chkCreateDate = chkCreateDate;
    }

    
    @Column(name="IS_REGULAR_TIME", nullable=false, length=5)
    public String getIsRegularTime() {
        return this.isRegularTime;
    }
    
    public void setIsRegularTime(String isRegularTime) {
        this.isRegularTime = isRegularTime;
    }

    
    @Column(name="BEFORE_CREATE_DATE", length=10)
    public String getBeforeCreateDate() {
        return this.beforeCreateDate;
    }
    
    public void setBeforeCreateDate(String beforeCreateDate) {
        this.beforeCreateDate = beforeCreateDate;
    }

    
    @Column(name="START_COUNT_TIME", length=10)
    public String getStartCountTime() {
        return this.startCountTime;
    }
    
    public void setStartCountTime(String startCountTime) {
        this.startCountTime = startCountTime;
    }




}


