package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/3/8 下午 05:47:19 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysOptionsComboId generated by hbm2java
 */
@Embeddable
public class SysOptionsComboId  implements java.io.Serializable {


     private String comboType;
     private String comboValue;

    public SysOptionsComboId() {
    }

    public SysOptionsComboId(String comboType, String comboValue) {
       this.comboType = comboType;
       this.comboValue = comboValue;
    }
   


    @Column(name="COMBO_TYPE", nullable=false, length=20)
    public String getComboType() {
        return this.comboType;
    }
    
    public void setComboType(String comboType) {
        this.comboType = comboType;
    }


    @Column(name="COMBO_VALUE", nullable=false, length=100)
    public String getComboValue() {
        return this.comboValue;
    }
    
    public void setComboValue(String comboValue) {
        this.comboValue = comboValue;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysOptionsComboId) ) return false;
		 SysOptionsComboId castOther = ( SysOptionsComboId ) other; 
         
		 return ( (this.getComboType()==castOther.getComboType()) || ( this.getComboType()!=null && castOther.getComboType()!=null && this.getComboType().equals(castOther.getComboType()) ) )
 && ( (this.getComboValue()==castOther.getComboValue()) || ( this.getComboValue()!=null && castOther.getComboValue()!=null && this.getComboValue().equals(castOther.getComboValue()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getComboType() == null ? 0 : this.getComboType().hashCode() );
         result = 37 * result + ( getComboValue() == null ? 0 : this.getComboValue().hashCode() );
         return result;
   }   


}


