package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysOrderStatusSetting generated by hbm2java
 */
@Entity
@Table(name="SYS_ORDER_STATUS_SETTING")
public class SysOrderStatusSetting  implements java.io.Serializable {


     private String statusId;
     private String statusName;
     private String lightColor;
     private String isOperateRecords;
     private String isKpi;
     private String description;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public SysOrderStatusSetting() {
    }

	
    public SysOrderStatusSetting(String statusId, String statusName, String isOperateRecords, String isKpi, Date createDate, String createUser) {
        this.statusId = statusId;
        this.statusName = statusName;
        this.isOperateRecords = isOperateRecords;
        this.isKpi = isKpi;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public SysOrderStatusSetting(String statusId, String statusName, String lightColor, String isOperateRecords, String isKpi, String description, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.statusId = statusId;
       this.statusName = statusName;
       this.lightColor = lightColor;
       this.isOperateRecords = isOperateRecords;
       this.isKpi = isKpi;
       this.description = description;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id 

    
    @Column(name="STATUS_ID", unique=true, nullable=false, length=10)
    public String getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }

    
    @Column(name="STATUS_NAME", nullable=false, length=100)
    public String getStatusName() {
        return this.statusName;
    }
    
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    
    @Column(name="LIGHT_COLOR", length=10)
    public String getLightColor() {
        return this.lightColor;
    }
    
    public void setLightColor(String lightColor) {
        this.lightColor = lightColor;
    }

    
    @Column(name="IS_OPERATE_RECORDS", nullable=false, length=5)
    public String getIsOperateRecords() {
        return this.isOperateRecords;
    }
    
    public void setIsOperateRecords(String isOperateRecords) {
        this.isOperateRecords = isOperateRecords;
    }

    
    @Column(name="IS_KPI", nullable=false, length=5)
    public String getIsKpi() {
        return this.isKpi;
    }
    
    public void setIsKpi(String isKpi) {
        this.isKpi = isKpi;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


