package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 ¤U¤È 01:10:48 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysProdTypeMapId generated by hbm2java
 */
@Embeddable
public class SysProdTypeMapId  implements java.io.Serializable {


     private String sourceSysId;
     private String sourceProdTypeId;

    public SysProdTypeMapId() {
    }

    public SysProdTypeMapId(String sourceSysId, String sourceProdTypeId) {
       this.sourceSysId = sourceSysId;
       this.sourceProdTypeId = sourceProdTypeId;
    }
   


    @Column(name="SOURCE_SYS_ID", nullable=false, length=20)
    public String getSourceSysId() {
        return this.sourceSysId;
    }
    
    public void setSourceSysId(String sourceSysId) {
        this.sourceSysId = sourceSysId;
    }


    @Column(name="SOURCE_PROD_TYPE_ID", nullable=false, length=50)
    public String getSourceProdTypeId() {
        return this.sourceProdTypeId;
    }
    
    public void setSourceProdTypeId(String sourceProdTypeId) {
        this.sourceProdTypeId = sourceProdTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysProdTypeMapId) ) return false;
		 SysProdTypeMapId castOther = ( SysProdTypeMapId ) other; 
         
		 return ( (this.getSourceSysId()==castOther.getSourceSysId()) || ( this.getSourceSysId()!=null && castOther.getSourceSysId()!=null && this.getSourceSysId().equals(castOther.getSourceSysId()) ) )
 && ( (this.getSourceProdTypeId()==castOther.getSourceProdTypeId()) || ( this.getSourceProdTypeId()!=null && castOther.getSourceProdTypeId()!=null && this.getSourceProdTypeId().equals(castOther.getSourceProdTypeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSourceSysId() == null ? 0 : this.getSourceSysId().hashCode() );
         result = 37 * result + ( getSourceProdTypeId() == null ? 0 : this.getSourceProdTypeId().hashCode() );
         return result;
   }   


}


