package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 ¤U¤È 01:10:48 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysRoleManualMappingId generated by hbm2java
 */
@Embeddable
public class SysRoleManualMappingId  implements java.io.Serializable {


     private String roleId;
     private String empno;

    public SysRoleManualMappingId() {
    }

    public SysRoleManualMappingId(String roleId, String empno) {
       this.roleId = roleId;
       this.empno = empno;
    }
   


    @Column(name="ROLE_ID", nullable=false, length=20)
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }


    @Column(name="EMPNO", nullable=false, length=20)
    public String getEmpno() {
        return this.empno;
    }
    
    public void setEmpno(String empno) {
        this.empno = empno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysRoleManualMappingId) ) return false;
		 SysRoleManualMappingId castOther = ( SysRoleManualMappingId ) other; 
         
		 return ( (this.getRoleId()==castOther.getRoleId()) || ( this.getRoleId()!=null && castOther.getRoleId()!=null && this.getRoleId().equals(castOther.getRoleId()) ) )
 && ( (this.getEmpno()==castOther.getEmpno()) || ( this.getEmpno()!=null && castOther.getEmpno()!=null && this.getEmpno().equals(castOther.getEmpno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRoleId() == null ? 0 : this.getRoleId().hashCode() );
         result = 37 * result + ( getEmpno() == null ? 0 : this.getEmpno().hashCode() );
         return result;
   }   


}


