package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysRoleMenuRef generated by hbm2java
 */
@Entity
@Table(name="SYS_ROLE_MENU_REF")
public class SysRoleMenuRef  implements java.io.Serializable {


     private SysRoleMenuRefId id;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public SysRoleMenuRef() {
    }

	
    public SysRoleMenuRef(SysRoleMenuRefId id, Date createDate, String createUser) {
        this.id = id;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public SysRoleMenuRef(SysRoleMenuRefId id, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.id = id;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="roleId", column=@Column(name="ROLE_ID", nullable=false, length=20) ), 
        @AttributeOverride(name="menuId", column=@Column(name="MENU_ID", nullable=false, length=40) ) } )
    public SysRoleMenuRefId getId() {
        return this.id;
    }
    
    public void setId(SysRoleMenuRefId id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


