package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 ¤U¤È 01:10:48 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysSkillMemberRefId generated by hbm2java
 */
@Embeddable
public class SysSkillMemberRefId  implements java.io.Serializable {


     private String skillId;
     private String empno;

    public SysSkillMemberRefId() {
    }

    public SysSkillMemberRefId(String skillId, String empno) {
       this.skillId = skillId;
       this.empno = empno;
    }
   


    @Column(name="SKILL_ID", nullable=false, length=40)
    public String getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(String skillId) {
        this.skillId = skillId;
    }


    @Column(name="EMPNO", nullable=false, length=20)
    public String getEmpno() {
        return this.empno;
    }
    
    public void setEmpno(String empno) {
        this.empno = empno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysSkillMemberRefId) ) return false;
		 SysSkillMemberRefId castOther = ( SysSkillMemberRefId ) other; 
         
		 return ( (this.getSkillId()==castOther.getSkillId()) || ( this.getSkillId()!=null && castOther.getSkillId()!=null && this.getSkillId().equals(castOther.getSkillId()) ) )
 && ( (this.getEmpno()==castOther.getEmpno()) || ( this.getEmpno()!=null && castOther.getEmpno()!=null && this.getEmpno().equals(castOther.getEmpno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSkillId() == null ? 0 : this.getSkillId().hashCode() );
         result = 37 * result + ( getEmpno() == null ? 0 : this.getEmpno().hashCode() );
         return result;
   }   


}


