package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysSkillMemberRef generated by hbm2java
 */
@Entity
@Table(name="SYS_SKILL_MEMBER_REF")
public class SysSkillMemberRef  implements java.io.Serializable {


     private SysSkillMemberRefId id;
     private String skillName;
     private String empname;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public SysSkillMemberRef() {
    }

	
    public SysSkillMemberRef(SysSkillMemberRefId id, String skillName, Date createDate, String createUser) {
        this.id = id;
        this.skillName = skillName;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public SysSkillMemberRef(SysSkillMemberRefId id, String skillName, String empname, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.id = id;
       this.skillName = skillName;
       this.empname = empname;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="skillId", column=@Column(name="SKILL_ID", nullable=false, length=40) ), 
        @AttributeOverride(name="empno", column=@Column(name="EMPNO", nullable=false, length=20) ) } )
    public SysSkillMemberRefId getId() {
        return this.id;
    }
    
    public void setId(SysSkillMemberRefId id) {
        this.id = id;
    }

    
    @Column(name="SKILL_NAME", nullable=false, length=50)
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }

    
    @Column(name="EMPNAME", length=50)
    public String getEmpname() {
        return this.empname;
    }
    
    public void setEmpname(String empname) {
        this.empname = empname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


