package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 ¤U¤È 01:10:48 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysShifttypeSkillMapId generated by hbm2java
 */
@Embeddable
public class SysShifttypeSkillMapId  implements java.io.Serializable {


     private String skillId;
     private String shiftTypeId;

    public SysShifttypeSkillMapId() {
    }

    public SysShifttypeSkillMapId(String skillId, String shiftTypeId) {
       this.skillId = skillId;
       this.shiftTypeId = shiftTypeId;
    }
   


    @Column(name="SKILL_ID", nullable=false, length=40)
    public String getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(String skillId) {
        this.skillId = skillId;
    }


    @Column(name="SHIFT_TYPE_ID", nullable=false, length=40)
    public String getShiftTypeId() {
        return this.shiftTypeId;
    }
    
    public void setShiftTypeId(String shiftTypeId) {
        this.shiftTypeId = shiftTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysShifttypeSkillMapId) ) return false;
		 SysShifttypeSkillMapId castOther = ( SysShifttypeSkillMapId ) other; 
         
		 return ( (this.getSkillId()==castOther.getSkillId()) || ( this.getSkillId()!=null && castOther.getSkillId()!=null && this.getSkillId().equals(castOther.getSkillId()) ) )
 && ( (this.getShiftTypeId()==castOther.getShiftTypeId()) || ( this.getShiftTypeId()!=null && castOther.getShiftTypeId()!=null && this.getShiftTypeId().equals(castOther.getShiftTypeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSkillId() == null ? 0 : this.getSkillId().hashCode() );
         result = 37 * result + ( getShiftTypeId() == null ? 0 : this.getShiftTypeId().hashCode() );
         return result;
   }   


}


