package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/6/16 下午 01:32:09 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysSurroundingDetailLog generated by hbm2java
 */
@Entity
@Table(name="SYS_SURROUNDING_DETAIL_LOG")
public class SysSurroundingDetailLog  implements java.io.Serializable {


     private String surroundingDId;
     private String surroundingMId;
     private String contentId;
     private String contentName;
     private String link;
     private String parameter;
     private Date createDate;
     private String createUser;

    public SysSurroundingDetailLog() {
    }

	
    public SysSurroundingDetailLog(String surroundingDId, String surroundingMId, Date createDate) {
        this.surroundingDId = surroundingDId;
        this.surroundingMId = surroundingMId;
        this.createDate = createDate;
    }
    public SysSurroundingDetailLog(String surroundingDId, String surroundingMId, String contentId, String contentName, String link, String parameter, Date createDate, String createUser) {
       this.surroundingDId = surroundingDId;
       this.surroundingMId = surroundingMId;
       this.contentId = contentId;
       this.contentName = contentName;
       this.link = link;
       this.parameter = parameter;
       this.createDate = createDate;
       this.createUser = createUser;
    }
   
     @Id 

    
    @Column(name="SURROUNDING_D_ID", unique=true, nullable=false, length=36)
    public String getSurroundingDId() {
        return this.surroundingDId;
    }
    
    public void setSurroundingDId(String surroundingDId) {
        this.surroundingDId = surroundingDId;
    }

    
    @Column(name="SURROUNDING_M_ID", nullable=false, length=36)
    public String getSurroundingMId() {
        return this.surroundingMId;
    }
    
    public void setSurroundingMId(String surroundingMId) {
        this.surroundingMId = surroundingMId;
    }

    
    @Column(name="CONTENT_ID", length=10)
    public String getContentId() {
        return this.contentId;
    }
    
    public void setContentId(String contentId) {
        this.contentId = contentId;
    }

    
    @Column(name="CONTENT_NAME", length=100)
    public String getContentName() {
        return this.contentName;
    }
    
    public void setContentName(String contentName) {
        this.contentName = contentName;
    }

    
    @Column(name="LINK", length=500)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    
    @Column(name="PARAMETER", length=500)
    public String getParameter() {
        return this.parameter;
    }
    
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", length=12)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }




}


