package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 �U�� 01:10:48 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysShifttypeSetting generated by hbm2java
 */
@Entity
@Table(name="SYS_SHIFTTYPE_SETTING")
public class SysShifttypeSetting  implements java.io.Serializable {


     private String shiftTypeId;
     private String shiftTypeName;
     private String startTime;
     private String endTime;
     private String breakStartTime;
     private String breakEndTime;
     private String description;
     private Date createDate;
     private String createUser;
     private Date updateDate;
     private String updateUser;

    public SysShifttypeSetting() {
    }

	
    public SysShifttypeSetting(String shiftTypeId, String shiftTypeName, String startTime, String endTime, String breakStartTime, String breakEndTime, Date createDate, String createUser) {
        this.shiftTypeId = shiftTypeId;
        this.shiftTypeName = shiftTypeName;
        this.startTime = startTime;
        this.endTime = endTime;
        this.breakStartTime = breakStartTime;
        this.breakEndTime = breakEndTime;
        this.createDate = createDate;
        this.createUser = createUser;
    }
    public SysShifttypeSetting(String shiftTypeId, String shiftTypeName, String startTime, String endTime, String breakStartTime, String breakEndTime, String description, Date createDate, String createUser, Date updateDate, String updateUser) {
       this.shiftTypeId = shiftTypeId;
       this.shiftTypeName = shiftTypeName;
       this.startTime = startTime;
       this.endTime = endTime;
       this.breakStartTime = breakStartTime;
       this.breakEndTime = breakEndTime;
       this.description = description;
       this.createDate = createDate;
       this.createUser = createUser;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
    }
   
     @Id 

    
    @Column(name="SHIFT_TYPE_ID", unique=true, nullable=false, length=40)
    public String getShiftTypeId() {
        return this.shiftTypeId;
    }
    
    public void setShiftTypeId(String shiftTypeId) {
        this.shiftTypeId = shiftTypeId;
    }

    
    @Column(name="SHIFT_TYPE_NAME", nullable=false, length=40)
    public String getShiftTypeName() {
        return this.shiftTypeName;
    }
    
    public void setShiftTypeName(String shiftTypeName) {
        this.shiftTypeName = shiftTypeName;
    }

    
    @Column(name="START_TIME", nullable=false, length=20)
    public String getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    
    @Column(name="END_TIME", nullable=false, length=20)
    public String getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="BREAK_START_TIME", nullable=false, length=20)
    public String getBreakStartTime() {
        return this.breakStartTime;
    }
    
    public void setBreakStartTime(String breakStartTime) {
        this.breakStartTime = breakStartTime;
    }

    
    @Column(name="BREAK_END_TIME", nullable=false, length=20)
    public String getBreakEndTime() {
        return this.breakEndTime;
    }
    
    public void setBreakEndTime(String breakEndTime) {
        this.breakEndTime = breakEndTime;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", nullable=false, length=20)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", length=20)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}


