package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/2/24 ¤U¤È 01:10:48 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysShiftContentId generated by hbm2java
 */
@Embeddable
public class SysShiftContentId  implements java.io.Serializable {


     private Date workDate;
     private String shiftTypeId;
     private String empno;

    public SysShiftContentId() {
    }

    public SysShiftContentId(Date workDate, String shiftTypeId, String empno) {
       this.workDate = workDate;
       this.shiftTypeId = shiftTypeId;
       this.empno = empno;
    }
   


    @Column(name="WORK_DATE", nullable=false, length=7)
    public Date getWorkDate() {
        return this.workDate;
    }
    
    public void setWorkDate(Date workDate) {
        this.workDate = workDate;
    }


    @Column(name="SHIFT_TYPE_ID", nullable=false, length=40)
    public String getShiftTypeId() {
        return this.shiftTypeId;
    }
    
    public void setShiftTypeId(String shiftTypeId) {
        this.shiftTypeId = shiftTypeId;
    }


    @Column(name="EMPNO", nullable=false, length=20)
    public String getEmpno() {
        return this.empno;
    }
    
    public void setEmpno(String empno) {
        this.empno = empno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysShiftContentId) ) return false;
		 SysShiftContentId castOther = ( SysShiftContentId ) other; 
         
		 return ( (this.getWorkDate()==castOther.getWorkDate()) || ( this.getWorkDate()!=null && castOther.getWorkDate()!=null && this.getWorkDate().equals(castOther.getWorkDate()) ) )
 && ( (this.getShiftTypeId()==castOther.getShiftTypeId()) || ( this.getShiftTypeId()!=null && castOther.getShiftTypeId()!=null && this.getShiftTypeId().equals(castOther.getShiftTypeId()) ) )
 && ( (this.getEmpno()==castOther.getEmpno()) || ( this.getEmpno()!=null && castOther.getEmpno()!=null && this.getEmpno().equals(castOther.getEmpno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getWorkDate() == null ? 0 : this.getWorkDate().hashCode() );
         result = 37 * result + ( getShiftTypeId() == null ? 0 : this.getShiftTypeId().hashCode() );
         result = 37 * result + ( getEmpno() == null ? 0 : this.getEmpno().hashCode() );
         return result;
   }   


}


