package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/6/16 下午 01:32:09 by Hibernate Tools 4.0.0


import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysSurroundingMainLog generated by hbm2java
 */
@Entity
@Table(name="SYS_SURROUNDING_MAIN_LOG")
public class SysSurroundingMainLog  implements java.io.Serializable {


     private String surroundingMId;
     private String orderMId;
     private String ownId;
     private String ownInfo;
     private String usingMsisdn;
     private String agentInfo;
     private String currUsingInfo;
     private Clob crmProfileIdviewInfo;
     private Date createDate;
     private String createUser;

    public SysSurroundingMainLog() {
    }

	
    public SysSurroundingMainLog(String surroundingMId, String orderMId, Date createDate) {
        this.surroundingMId = surroundingMId;
        this.orderMId = orderMId;
        this.createDate = createDate;
    }
    public SysSurroundingMainLog(String surroundingMId, String orderMId, String ownId, String ownInfo, String usingMsisdn, String agentInfo, String currUsingInfo, Clob crmProfileIdviewInfo, Date createDate, String createUser) {
       this.surroundingMId = surroundingMId;
       this.orderMId = orderMId;
       this.ownId = ownId;
       this.ownInfo = ownInfo;
       this.usingMsisdn = usingMsisdn;
       this.agentInfo = agentInfo;
       this.currUsingInfo = currUsingInfo;
       this.crmProfileIdviewInfo = crmProfileIdviewInfo;
       this.createDate = createDate;
       this.createUser = createUser;
    }
   
     @Id 

    
    @Column(name="SURROUNDING_M_ID", unique=true, nullable=false, length=36)
    public String getSurroundingMId() {
        return this.surroundingMId;
    }
    
    public void setSurroundingMId(String surroundingMId) {
        this.surroundingMId = surroundingMId;
    }

    
    @Column(name="ORDER_M_ID", nullable=false, length=36)
    public String getOrderMId() {
        return this.orderMId;
    }
    
    public void setOrderMId(String orderMId) {
        this.orderMId = orderMId;
    }

    
    @Column(name="OWN_ID", length=100)
    public String getOwnId() {
        return this.ownId;
    }
    
    public void setOwnId(String ownId) {
        this.ownId = ownId;
    }

    
    @Column(name="OWN_INFO", length=4000)
    public String getOwnInfo() {
        return this.ownInfo;
    }
    
    public void setOwnInfo(String ownInfo) {
        this.ownInfo = ownInfo;
    }

    
    @Column(name="USING_MSISDN", length=4000)
    public String getUsingMsisdn() {
        return this.usingMsisdn;
    }
    
    public void setUsingMsisdn(String usingMsisdn) {
        this.usingMsisdn = usingMsisdn;
    }

    
    @Column(name="AGENT_INFO", length=4000)
    public String getAgentInfo() {
        return this.agentInfo;
    }
    
    public void setAgentInfo(String agentInfo) {
        this.agentInfo = agentInfo;
    }

    
    @Column(name="CURR_USING_INFO", length=4000)
    public String getCurrUsingInfo() {
        return this.currUsingInfo;
    }
    
    public void setCurrUsingInfo(String currUsingInfo) {
        this.currUsingInfo = currUsingInfo;
    }

    
    @Column(name="CRM_PROFILE_IDVIEW_INFO")
    public Clob getCrmProfileIdviewInfo() {
        return this.crmProfileIdviewInfo;
    }
    
    public void setCrmProfileIdviewInfo(Clob crmProfileIdviewInfo) {
        this.crmProfileIdviewInfo = crmProfileIdviewInfo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="CREATE_USER", length=12)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }




}


