package com.fet.crm.osp.platform.core.db.model;
// Generated May 19, 2017 2:00:46 PM by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysTxidMap generated by hbm2java
 */
@Entity
@Table(name="SYS_TXID_MAP")
public class SysTxidMap  implements java.io.Serializable {


     private SysTxidMapId id;
     private String txid;
     private Date createDate;
     private Date updateDate;

    public SysTxidMap() {
    }

	
    public SysTxidMap(SysTxidMapId id, String txid, Date createDate) {
        this.id = id;
        this.txid = txid;
        this.createDate = createDate;
    }
    public SysTxidMap(SysTxidMapId id, String txid, Date createDate, Date updateDate) {
       this.id = id;
       this.txid = txid;
       this.createDate = createDate;
       this.updateDate = updateDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ospKey", column=@Column(name="OSP_KEY", nullable=false, length=36) ), 
        @AttributeOverride(name="orderMId", column=@Column(name="ORDER_M_ID", nullable=false, length=36) ) } )
    public SysTxidMapId getId() {
        return this.id;
    }
    
    public void setId(SysTxidMapId id) {
        this.id = id;
    }

    
    @Column(name="TXID", length=36)
    public String getTxid() {
        return this.txid;
    }
    
    public void setTxid(String txid) {
        this.txid = txid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


