package com.fet.crm.osp.platform.core.db.model;
// Generated 2017/3/23 下午 02:35:57 by Hibernate Tools 4.0.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysTxid generated by hbm2java
 */
@Entity
@Table(name="SYS_TXID")
public class SysTxid  implements java.io.Serializable {


     private String txid;
     private String orderPoolKey;
     private Date createDate;
     private Date updateDate;

    public SysTxid() {
    }

	
    public SysTxid(String txid, String orderPoolKey, Date createDate) {
        this.txid = txid;
        this.orderPoolKey = orderPoolKey;
        this.createDate = createDate;
    }
    public SysTxid(String txid, String orderPoolKey, Date createDate, Date updateDate) {
       this.txid = txid;
       this.orderPoolKey = orderPoolKey;
       this.createDate = createDate;
       this.updateDate = updateDate;
    }
   
     @Id 

    
    @Column(name="TXID", unique=true, nullable=false, length=36)
    public String getTxid() {
        return this.txid;
    }
    
    public void setTxid(String txid) {
        this.txid = txid;
    }

    
    @Column(name="ORDER_POOL_KEY", nullable=false, length=36)
    public String getOrderPoolKey() {
        return this.orderPoolKey;
    }
    
    public void setOrderPoolKey(String orderPoolKey) {
        this.orderPoolKey = orderPoolKey;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


