package com.fet.crm.osp.platform.core.db.model;
// Generated May 19, 2017 2:00:46 PM by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysTxidMapId generated by hbm2java
 */
@Embeddable
public class SysTxidMapId  implements java.io.Serializable {


     private String ospKey;
     private String orderMId;

    public SysTxidMapId() {
    }

    public SysTxidMapId(String ospKey, String orderMId) {
       this.ospKey = ospKey;
       this.orderMId = orderMId;
    }
   


    @Column(name="OSP_KEY", nullable=false, length=36)
    public String getOspKey() {
        return this.ospKey;
    }
    
    public void setOspKey(String ospKey) {
        this.ospKey = ospKey;
    }


    @Column(name="ORDER_M_ID", nullable=false, length=36)
    public String getOrderMId() {
        return this.orderMId;
    }
    
    public void setOrderMId(String orderMId) {
        this.orderMId = orderMId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SysTxidMapId) ) return false;
		 SysTxidMapId castOther = ( SysTxidMapId ) other; 
         
		 return ( (this.getOspKey()==castOther.getOspKey()) || ( this.getOspKey()!=null && castOther.getOspKey()!=null && this.getOspKey().equals(castOther.getOspKey()) ) )
 && ( (this.getOrderMId()==castOther.getOrderMId()) || ( this.getOrderMId()!=null && castOther.getOrderMId()!=null && this.getOrderMId().equals(castOther.getOrderMId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOspKey() == null ? 0 : this.getOspKey().hashCode() );
         result = 37 * result + ( getOrderMId() == null ? 0 : this.getOrderMId().hashCode() );
         return result;
   }   


}


