package com.fet.crm.osp.kernel.core.db.model.osp;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DispatchEntityConfigId generated by hbm2java
 */
@Embeddable
public class DispatchEntityConfigId implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private String teamGroup;
    private String dispConfigKey;

    public DispatchEntityConfigId() {
    }

    public DispatchEntityConfigId(String teamGroup, String dispConfigKey) {
        this.teamGroup = teamGroup;
        this.dispConfigKey = dispConfigKey;
    }

    @Column(name = "TEAM_GROUP", nullable = false, length = 5)
    public String getTeamGroup() {
        return this.teamGroup;
    }

    public void setTeamGroup(String teamGroup) {
        this.teamGroup = teamGroup;
    }

    @Column(name = "DISP_CONFIG_KEY", nullable = false, length = 50)
    public String getDispConfigKey() {
        return this.dispConfigKey;
    }

    public void setDispConfigKey(String dispConfigKey) {
        this.dispConfigKey = dispConfigKey;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof DispatchEntityConfigId))
            return false;
        DispatchEntityConfigId castOther = (DispatchEntityConfigId) other;

        return ((this.getTeamGroup() == castOther.getTeamGroup()) || (this.getTeamGroup() != null
                && castOther.getTeamGroup() != null && this.getTeamGroup().equals(castOther.getTeamGroup())))
                && ((this.getDispConfigKey() == castOther.getDispConfigKey())
                        || (this.getDispConfigKey() != null && castOther.getDispConfigKey() != null
                                && this.getDispConfigKey().equals(castOther.getDispConfigKey())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getTeamGroup() == null ? 0 : this.getTeamGroup().hashCode());
        result = 37 * result + (getDispConfigKey() == null ? 0 : this.getDispConfigKey().hashCode());
        return result;
    }

}
