package com.fet.crm.osp.kernel.core.db.model.osp;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DispatchEntityConfig generated by hbm2java
 */
@Entity
@Table(name = "DISPATCH_ENTITY_CONFIG")
public class DispatchEntityConfig implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private DispatchEntityConfigId id;
    private String dispConfigValue;
    private String description;
    private Date createDate;
    private String createUser;
    private Date updateDate;
    private String updateUser;

    public DispatchEntityConfig() {
    }

    public DispatchEntityConfig(DispatchEntityConfigId id, String dispConfigValue, Date createDate, String createUser) {
        this.id = id;
        this.dispConfigValue = dispConfigValue;
        this.createDate = createDate;
        this.createUser = createUser;
    }

    public DispatchEntityConfig(DispatchEntityConfigId id, String dispConfigValue, String description, Date createDate,
            String createUser, Date updateDate, String updateUser) {
        this.id = id;
        this.dispConfigValue = dispConfigValue;
        this.description = description;
        this.createDate = createDate;
        this.createUser = createUser;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "teamGroup", column = @Column(name = "TEAM_GROUP", nullable = false, length = 5) ),
            @AttributeOverride(name = "dispConfigKey", column = @Column(name = "DISP_CONFIG_KEY", nullable = false, length = 50) ) })
    public DispatchEntityConfigId getId() {
        return this.id;
    }

    public void setId(DispatchEntityConfigId id) {
        this.id = id;
    }

    @Column(name = "DISP_CONFIG_VALUE", nullable = false, length = 50)
    public String getDispConfigValue() {
        return this.dispConfigValue;
    }

    public void setDispConfigValue(String dispConfigValue) {
        this.dispConfigValue = dispConfigValue;
    }

    @Column(name = "DESCRIPTION", length = 500)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DATE", nullable = false, length = 7)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "CREATE_USER", nullable = false, length = 20)
    public String getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DATE", length = 7)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Column(name = "UPDATE_USER", length = 20)
    public String getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

}
