package com.fet.crm.osp.kernel.core.db.model.osp;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderDetailSpv generated by hbm2java
 */
@Entity
@Table(name = "ORDER_DETAIL_SPV")
public class OrderDetailSpv implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private String orderDId;
    private String poolKey;
    private String sourceOrderId;
    private String accountId;
    private String msisdn;
    private String cycleCode;
    private String cancelReason;
    private String opid;
    private String channel;
    private String serviceName;
    private String offerId;
    private String offerName;
    private String taskStatus;
    private Date statusTime;
    private Date requestEffectiveDate;
    private Date requestExpirationDate;
    private Date taskCreationDate;
    private String taskSeqNo;
    private String taskId;
    private Date createDate;
    private String createUser;
    private Date updateDate;
    private String updateUser;

    public OrderDetailSpv() {
    }

    public OrderDetailSpv(String orderDId, String poolKey, String sourceOrderId, Date createDate) {
        this.orderDId = orderDId;
        this.poolKey = poolKey;
        this.sourceOrderId = sourceOrderId;
        this.createDate = createDate;
    }

    public OrderDetailSpv(String orderDId, String poolKey, String sourceOrderId, String accountId, String msisdn,
            String cycleCode, String cancelReason, String opid, String channel, String serviceName, String offerId,
            String offerName, String taskStatus, Date statusTime, Date requestEffectiveDate, Date requestExpirationDate,
            Date taskCreationDate, String taskSeqNo, String taskId, Date createDate, String createUser, Date updateDate,
            String updateUser) {
        this.orderDId = orderDId;
        this.poolKey = poolKey;
        this.sourceOrderId = sourceOrderId;
        this.accountId = accountId;
        this.msisdn = msisdn;
        this.cycleCode = cycleCode;
        this.cancelReason = cancelReason;
        this.opid = opid;
        this.channel = channel;
        this.serviceName = serviceName;
        this.offerId = offerId;
        this.offerName = offerName;
        this.taskStatus = taskStatus;
        this.statusTime = statusTime;
        this.requestEffectiveDate = requestEffectiveDate;
        this.requestExpirationDate = requestExpirationDate;
        this.taskCreationDate = taskCreationDate;
        this.taskSeqNo = taskSeqNo;
        this.taskId = taskId;
        this.createDate = createDate;
        this.createUser = createUser;
        this.updateDate = updateDate;
        this.updateUser = updateUser;
    }

    @Id

    @Column(name = "ORDER_D_ID", unique = true, nullable = false, length = 36)
    public String getOrderDId() {
        return this.orderDId;
    }

    public void setOrderDId(String orderDId) {
        this.orderDId = orderDId;
    }

    @Column(name = "POOL_KEY", nullable = false, length = 36)
    public String getPoolKey() {
        return this.poolKey;
    }

    public void setPoolKey(String poolKey) {
        this.poolKey = poolKey;
    }

    @Column(name = "SOURCE_ORDER_ID", nullable = false, length = 50)
    public String getSourceOrderId() {
        return this.sourceOrderId;
    }

    public void setSourceOrderId(String sourceOrderId) {
        this.sourceOrderId = sourceOrderId;
    }

    @Column(name = "ACCOUNT_ID", length = 50)
    public String getAccountId() {
        return this.accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    @Column(name = "MSISDN", length = 50)
    public String getMsisdn() {
        return this.msisdn;
    }

    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn;
    }

    @Column(name = "CYCLE_CODE", length = 10)
    public String getCycleCode() {
        return this.cycleCode;
    }

    public void setCycleCode(String cycleCode) {
        this.cycleCode = cycleCode;
    }

    @Column(name = "CANCEL_REASON", length = 10)
    public String getCancelReason() {
        return this.cancelReason;
    }

    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason;
    }

    @Column(name = "OPID", length = 20)
    public String getOpid() {
        return this.opid;
    }

    public void setOpid(String opid) {
        this.opid = opid;
    }

    @Column(name = "CHANNEL", length = 40)
    public String getChannel() {
        return this.channel;
    }

    public void setChannel(String channel) {
        this.channel = channel;
    }

    @Column(name = "SERVICE_NAME", length = 60)
    public String getServiceName() {
        return this.serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    @Column(name = "OFFER_ID", length = 20)
    public String getOfferId() {
        return this.offerId;
    }

    public void setOfferId(String offerId) {
        this.offerId = offerId;
    }

    @Column(name = "OFFER_NAME", length = 500)
    public String getOfferName() {
        return this.offerName;
    }

    public void setOfferName(String offerName) {
        this.offerName = offerName;
    }

    @Column(name = "TASK_STATUS", length = 10)
    public String getTaskStatus() {
        return this.taskStatus;
    }

    public void setTaskStatus(String taskStatus) {
        this.taskStatus = taskStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "STATUS_TIME", length = 7)
    public Date getStatusTime() {
        return this.statusTime;
    }

    public void setStatusTime(Date statusTime) {
        this.statusTime = statusTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "REQUEST_EFFECTIVE_DATE", length = 7)
    public Date getRequestEffectiveDate() {
        return this.requestEffectiveDate;
    }

    public void setRequestEffectiveDate(Date requestEffectiveDate) {
        this.requestEffectiveDate = requestEffectiveDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "REQUEST_EXPIRATION_DATE", length = 7)
    public Date getRequestExpirationDate() {
        return this.requestExpirationDate;
    }

    public void setRequestExpirationDate(Date requestExpirationDate) {
        this.requestExpirationDate = requestExpirationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "TASK_CREATION_DATE", length = 7)
    public Date getTaskCreationDate() {
        return this.taskCreationDate;
    }

    public void setTaskCreationDate(Date taskCreationDate) {
        this.taskCreationDate = taskCreationDate;
    }

    @Column(name = "TASK_SEQ_NO", length = 30)
    public String getTaskSeqNo() {
        return this.taskSeqNo;
    }

    public void setTaskSeqNo(String taskSeqNo) {
        this.taskSeqNo = taskSeqNo;
    }

    @Column(name = "TASK_ID", length = 30)
    public String getTaskId() {
        return this.taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DATE", nullable = false, length = 7)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "CREATE_USER", length = 20)
    public String getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DATE", length = 7)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Column(name = "UPDATE_USER", length = 20)
    public String getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

}
