SELECT
    T1.CONTENT_ID    AS CONTENT_ID,
    T1.ITEM_ID       AS ITEM_ID,
    T1.SORT_SEQUENCE AS SORT_SEQUENCE,
    T1.UNIT          AS UNIT,
    T2.ITEM_TYPE     AS ITEM_TYPE,
    T2.ITEM_NAME     AS ITEM_NAME,
    T3.ITEM_VALUE    AS ITEM_VALUE,
    T3.CREATE_DATE   AS CREATE_DATE
FROM
    BUZ_CONTENT_ITEM_MAP T1
LEFT JOIN
    BUZ_ITEM T2
ON
    T1.ITEM_ID = T2.ITEM_ID
LEFT JOIN
    (
        SELECT
            ITEM_ID     AS ITEM_ID,
            ITEM_VALUE  AS ITEM_VALUE,
            CREATE_DATE AS CREATE_DATE
        FROM
            BUZ_RECORD_ROUTINE
        WHERE
            PROCESS_USER_ID = :PROCESS_USER_ID
        AND PROCESS_DATE LIKE SYSDATE) T3
ON
    T2.ITEM_ID = T3.ITEM_ID
WHERE
    T1.CONTENT_ID = :CONTENT_ID
ORDER BY
    T1.SORT_SEQUENCE